### ISSUE TITLE
Broadcasts in Mobile App (android)

### ISSUE THREAD

**Issue by Ehsynli** [lichess-org/lichobile#1079]
**I'm submitting a ...** 

# Feature request

- In Mobile app (Android) we are not able to see the broadcasts which are the real Chess Games by Masters. 
- Mobile App is very Useful and it would be more useful if we see them to follow the games. 
- The Feature does not change the App, only adds a new Function which will increase the usage of the Application.

**Comment by jas14** [comment]
Duplicate of #1284
