### ISSUE TITLE
Enable creating seeks with minimum rating 600

### ISSUE THREAD

**Issue by ddugovic** [lichess-org/lichobile#1136]
Lichess' minimum rating is 600:
https://github.com/ornicar/lila/commit/b248195f9bd4b1539d4078e903cff28d661569e3
https://lichess.org/forum/lichess-feedback/when-you-are-looking-for-a-new-opponent-the-rating-range-on-the-app-goes-only-down-to-800

https://github.com/veloce/lichobile/blob/802f2699ab7740c5cf92c93be8417b1806172fc1/src/settings.ts#L288

**Comment by veloce** [comment]
No more relevant with new rating range system.
