### ISSUE TITLE
Feature Request:Notation Formatting- Use of color in analysis

### ISSUE THREAD

**Issue by jdruding** [lichess-org/lichobile#1174]
**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

On mobile, the way the notation runs on with multiple pairs of turns in the same row makes it difficult to pick out your inaccuracies, mistakes and blunders when you are performing an analysis. I would like to see the use of color on both mobile and non mobile for inaccuracies, mistakes and blunders. Having those items color coded would make it much easier to scan over the PGN and to jump right to those items.

**Comment by jas14** [comment]
Complete as of [v7.9.0](https://github.com/lichess-org/lichobile/releases/tag/v7.9.0)!
