### ISSUE TITLE
Rabbit icon - failure to check cultural translation

### ISSUE THREAD

**Issue by Tim-Wilkinson** [lichess-org/lichobile#1205]
feature request (design)

Change the rabbit logo. To chess players in the UK 'rabbit' or 'bunny' is the standard derogatory term for a weak player, with an implication of timidity. It is not immediately clear what the icon is supposed to indicate and it gives the initial impression that the user is being classified as a weak player. Even on googling the icon to find out what it is supposed to mean the impression lingers that users of rapid time controls are being denigrated as weak.

A rabbit has no connection with 'rapidity' (or rapid chess) except similarity in the words (in English). Referring to the words to determine the point of the icon presumably defeats the point of using pictorial symbols to communicate. 

In any case 'rapid' chess is actually medium-speed by online standards. Perhaps an icon that represents the strengths of rapid time controls - fits into a busy life while also allowing time for some reasonably deep calculation of moves - would be more suitable. I'm sure the design team is capable of devising something that fits that bill, rather than relying on feeble language-specific word play and inadvertently insulting a section of site users.

**Comment by jas14** [comment]
This is consistent with the design language on the website, see https://github.com/lichess-org/lila/issues/7167#issuecomment-678757645 for similar discussion.
