### ISSUE TITLE
Puzzle rating graph shows one erroneous very low point

### ISSUE THREAD

**Issue by joostmeulenbeld** [lichess-org/lichobile#1233]
# Bug report

**Current behavior:**
The graph showing my puzzle rating over time always contains one very low point just before the current rating. This is a faulty point since my rating has nog been that low for a while. (See image below)
![Screenshot_20200512-143108](https://user-images.githubusercontent.com/2323661/81691923-e995cf00-945d-11ea-892c-25e69b771205.jpg)

**Expected behavior:**
Graph should just show actual puzzle rating history

**Steps to reproduce:**
Look at puzzle rating in Android app

**Environment information**

- phone hardware: OnePlus 5t
- phone operating system version OxygenOS 9.0.11 (Android 9)
- version of lichess mobile 7.0.4

**Comment by jas14** [comment]
The app no longer shows the puzzle graph at all as of [7.6.1](https://github.com/lichess-org/lichobile/releases/tag/v7.6.1).
