### ISSUE TITLE
Tactical puzzles not awarding rating points

### ISSUE THREAD

**Issue by tomt28** [lichess-org/lichobile#1310]
**Describe the bug**
Tactical puzzles not awarding rating points for correct answers out removing rating points for incorrect answers. It was working for a long time then just stopped completely. Hasn't worked for weeks.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:  Sony  Xa1
 - OS: Android

**Additional context**

**Comment by MglMX** [comment]
There is a ªsync and refresh saved puzzles" button in the puzzles section. If you click it, the puzzle will be synced again and the ratings should work.

**Comment by jas14** [comment]
Duplicate of #1363
