### ISSUE TITLE
iOS loading screen in dark mode

### ISSUE THREAD

**Issue by tmmlaarhoven** [lichess-org/lichobile#1366]
When loading the app, briefly a loading screen appears with the lichess logo in black and white: a black lichess knight on a white background. When using dark mode however, wouldn't it make sense to use a negative of that, with a white knight on a black background? (It would be easier on the eyes at night, and more in line with the dark mode.)

**Is your feature request related to a problem? Please describe.**
Not so much a problem, but I like things to be dark on my phone, and not be blinded by light when opening the app at night.

**Describe the solution you'd like**
Change the loading screen for users in dark mode from the current one to its negative.

**Describe alternatives you've considered**
Not applicable. 

**Additional context**
I think the description above is clear enough.

**Comment by tmmlaarhoven** [comment]
Illustrative before and after images:

![Screenshot_20200908-234125](https://user-images.githubusercontent.com/11218275/92541515-8a4a9e80-f246-11ea-9c35-655c85f66076.jpg)

![image](https://user-images.githubusercontent.com/11218275/92541517-8ae33500-f246-11ea-9590-9766c1dc43a9.png)

**Comment by jas14** [comment]
Should be natively doable in Android and iOS, relevant Capacitor issue here: https://github.com/ionic-team/capacitor/issues/2947

**Comment by DaniSpringer** [comment]
Should not be hard. If I push such changes will you accept them? (I can do iOS)

**Comment by jas14** [comment]
@DaniSpringer yes, PRs are always welcome! Thanks

**Comment by DaniSpringer** [comment]
> @DaniSpringer yes, PRs are always welcome! Thanks

Hi, so I now notice that the app isn’t native? I only know pure swift + Xcode

**Comment by jas14** [comment]
Yes, the app is written mostly in cross-platform JS, using Capacitor as a framework. There are iOS and Android subdirectories for platform-specific things, though. You might start with the above-linked Capacitor issue for inspiration

**Comment by DaniSpringer** [comment]
> Yes, the app is written mostly in cross-platform JS, using Capacitor as a framework. There are iOS and Android subdirectories for platform-specific things, though. You might start with the above-linked Capacitor issue for inspiration

Any plans to make a native app? I believe I would be more helpful then. I don’t have the budget to learn new technologies after-hours at the moment, unfortunately.

**Comment by jas14** [comment]
Not to my knowledge

**Comment by ncodee** [comment]
Any reason why this hasn't been implemented yet? Surely, it should be a simple change.

**Comment by antonkratz** [comment]
A dark splash screen on iOS would be awesome to have especially at night.

**Comment by veloce** [comment]
Fixed now.
