### ISSUE TITLE
Email for registration filter is way to strikt. Many people can't use their primary email to register.

### ISSUE THREAD

**Issue by lucasonbe** [lichess-org/lichobile#1426]
**Describe the bug**
Email for registration filter is way to strikt. Many people can't use their primary email to register.

**To Reproduce**
Try to register an email with any .ws domain account. It fails. My domain is lathouwers.ws. None of my users can create a lichess account with their own email.

**Expected behavior**
I should be able to use my own email domain to register new accounts.

**Comment by jas14** [comment]
Email validation is controlled by the Lichess server. Please check the [lila](https://github.com/lichess-org/lila) repository for similar issues, and if there are none, you can open an issue over there.
