### ISSUE TITLE
Mobile app clock issue

### ISSUE THREAD

**Issue by nuwanda02** [lichess-org/lichobile#1456]
I just lost two games because the timer goes off at my opponent but then when I restarted the app I saw that my timer was off and I lost because of time out. I noticed that because of dropped rating.

Happened 2 times on 12/22/20. One of the games is:

https://lichess.org/gM1nsZPoA63I

**Comment by jas14** [comment]
This sounds like a network connectivity issue. If the app can't receive move messages from the server, it will seem like your opponent never moves, but in fact they may have moved.

**Comment by jas14** [comment]
Duplicate of #1344
