### ISSUE TITLE
puzzle 662741064

### ISSUE THREAD

**Issue by EsraX** [lichess-org/lichobile#1473]
**Describe the bug**
For some reason Qg8, though being checkmate is considered a losing move for this puzzle. 
(queen is covered by bishop, king cant go anywhere and no piece can take the queen) even stockfish doesnt give a move to play since it is checkmate.

**To Reproduce**
1. Go to puzzle 662741064
2. While on the mobile app play queen takes pawn f7 check, then play queen g8 checkmate. The app will give you an error and say you played the wrong move, the move it wants you to play is queen to f8 which admittedly is also checkmate.

https://imgur.com/arhnLeh
https://imgur.com/XyiG1Wl

**Expected behavior**
The expected behavior is that both moves are considered valid solutions to the puzzle.

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: 12.4.9
 - Version 7.6.0

**Comment by shawninder** [comment]
Qg8 is considered a success for me on both my devices:

- MacBook Pro (macOS Mojave 10.14.6) running Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- Android Samsung Galaxy A5 running Google Chrome for Android version 87.0.4280.101

Perhaps it's an iPhone thing?

**Comment by shawninder** [comment]
I would gladly test using the native Android app instead of the website, but I'm not sure how to find a specific puzzle in the app...

**Comment by jas14** [comment]
This was fixed in 245a40076865234a643c59da29c4c1f4d6dbf12d and [released](https://github.com/veloce/lichobile/commit/ab82ab4ad08e2dfe9a5da6ecb4729a2c443af4cc) as version 7.6.1.
