### ISSUE TITLE
Puzzle 28059326

### ISSUE THREAD

**Issue by blueshades33** [lichess-org/lichobile#1478]
When solving the puzzle, there are two obvious ways to checkmate the king. Only one is counted as correct, but both are unstoppable mate in 1. 

To recreate the bug. Play the puzzle. Go Qb1, then QxC1, then QxD1, the next move is where the bug is. If you play RxF1# then the puzzle is counted correct. But if you play QxF1# then it is counted wrong. 

I expect that if I got the correct solution to the puzzle (find the best move, AKA checkmate in this case) I should get credit for the correct answer.

playing on iPhone 12. 

I am not worried about the rating I lost being fixed, it is just very frustrating to run into these issues. Hopefully it can be fixed for future players, Thanks!

**Comment by jas14** [comment]
https://github.com/veloce/lichobile/issues/1473#issuecomment-753576103 - this should be fixed in 7.6.1, please upgrade

**Comment by ofmetal** [comment]
Same problem with 171920830.
Solving from web is Ok, solving from latest iOS app (v7.6.0 is the latest today) fails when checkmating with Queen (it must be Rook somehow).

**Comment by ofmetal** [comment]
It is ok, that tasks has several solutions, but too bad when some of the solutions are refused by the app.

**Comment by ofmetal** [comment]
More like this: 135549115 ( lichess.org/training/135549115 )
There are 6 ways to checkmate: Rg8#, Rg7#, Rg4#, Rg3#, Rg2#, Rg1#.
Somehow only Rg1# is good.

And almost like this (probably for all versions) 459084811
Classical 2-move checkmate sequence is unaccepted:
1. .. Qf1+
2. Rxf1 Rxf1#

It wants only Qxe1#.

[](url
![IMG_2299](https://user-images.githubusercontent.com/76742183/104089191-66a06f00-529f-11eb-8f96-6604e6f28d95.PNG)
![IMG_2300](https://user-images.githubusercontent.com/76742183/104089194-6c965000-529f-11eb-91df-66200d331706.PNG)

)

**Comment by jas14** [comment]
Fixed in 7.6.1, which has been out for quite some time now, closing as such
