### ISSUE TITLE
Not able to run locally

### ISSUE THREAD

**Issue by Geervan** [lichess-org/lichobile#1534]
when the run npm start and open localhost 8080/www i just see a black  colour screen in chrome

**Comment by freefal** [comment]
Hit F12 and switch to device mode.

**Comment by Geervan** [comment]
Thanks for commenting but I tried it and still nothing happned but I found  a error in the console of chrome it says 


 Failed to load resource: the server responded with a status of 404 (Not Found)          main.js:1

**Comment by jas14** [comment]
@Geervan still having this problem?

**Comment by Geervan** [comment]
Not anymore, ty for taking interest

**Comment by jas14** [comment]
👍
