### ISSUE TITLE
Please add practice to app

### ISSUE THREAD

**Issue by akarimia** [lichess-org/lichobile#1559]
Hi
In lichess.org there is a learn menu that is include basics, practice, pazzels and study parts but in lichess mobile app I can't find basics and practice, please add them to app.
Best wishes.

**Comment by arieltz23** [comment]
I would also love it if the practice menu at https://lichess.org/practice would be integrated into the app, I'm sure many other users would find it super helpful! :)

**Comment by shah-xad** [comment]
I also want this.

**Comment by jas14** [comment]
Duplicate of #759
