### ISSUE TITLE
Premove doesn't play sound correctly on iOS app

### ISSUE THREAD

**Issue by DaniSpringer** [lichess-org/lichobile#1701]
Premove doesn't play sound correctly if it's a capture

**Comment by jas14** [comment]
Hi @DaniSpringer , filling out the bug report template here would have been immensely helpful, as it might have included the following info:

- What sound did you hear, if any?
- What sound did you expect to hear, if any?
- Was the capture by you, or by your opponent?
- What version of iOS are you on?
- Did you notice that this was introduced in a particular app version, or has it been present as long as you've been using the app?

**Comment by DaniSpringer** [comment]
> Hi @DaniSpringer , filling out the bug report template here would have been immensely helpful, as it might have included the following info:
> 
> * What sound did you hear, if any? One move sound
> * What sound did you expect to hear, if any? Two moves sounds
> * Was the capture by you, or by your opponent? Doesn’t matter. Happens in both cases. Premoves after captures don’t play a sound. 
> * What version of iOS are you on? 14.6
> * Did you notice that this was introduced in a particular app version, or has it been present as long as you've been using the app? Always been present

**Comment by DaniSpringer** [comment]
@jas14 bump
