### ISSUE TITLE
Version number outside safe area

### ISSUE THREAD

**Issue by DaniSpringer** [lichess-org/lichobile#1702]
The "v7.11.1" is barely visible, should follow safe area rules instead
https://github.com/veloce/lichobile/blob/1faafb8a6766c9510f68ef8df124f77d8e46c8a5/src/ui/settings/settings.ts#L61

**Comment by DaniSpringer** [comment]
bump

**Comment by jas14** [comment]
@DaniSpringer , development on the Capacitor-based mobile app (this repository) is on pause with very few exceptions as [veloce works full-time on a rewrite in Flutter](https://lichess.org/blog/Y2Z47hEAAGUB7i7A/lichess-recruits-full-time-mobile-developer). Please don't "bump" issues, that just sends us a lot of emails.

**Comment by DaniSpringer** [comment]
> @DaniSpringer , development on the Capacitor-based mobile app (this repository) is on pause with very few exceptions as [veloce works full-time on a rewrite in Flutter](https://lichess.org/blog/Y2Z47hEAAGUB7i7A/lichess-recruits-full-time-mobile-developer). Please don't "bump" issues, that just sends us a lot of emails.

Sorry! Understood 

happy to help with the new app if I can

**Comment by jas14** [comment]
Development on the [new repo](https://github.com/lichess-org/mobile) is closed, but stay tuned — at some point in 2023, veloce hopes to release a first version, around which time I imagine the repo will be opened for bug reports etc and your feedback will be valuable!

**Comment by DaniSpringer** [comment]
Ok, thank you! We’ll be back…
