### ISSUE TITLE
Rating filter is not working

### ISSUE THREAD

**Issue by AlekseyLobanov** [lichess-org/lichobile#1727]
**Describe the bug**
Rating filters broken at least for me. My post on lichess forum: [url](https://lichess.org/forum/lichess-feedback/opponent-filters-broken)

**To Reproduce**
1. Go to New Game
2. Set Casual, -350 .. 0 rating filter, 1+0 control
3. Game with someone who has rating not in this interval

**Expected behavior**
I expect new game rating filters to work.

**Screenshots**
Check attached game in lichess forum post

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9t Pro
 - OS: Android, latest MiUI
 - Version latest

**Additional context**
I notices this about a week ago.

**Comment by jas14** [comment]
I believe this is fixed by f7f9a63f396303b425648448263e6ff2a4c2faa5

**Comment by AlekseyLobanov** [comment]
LGTM
