### ISSUE TITLE
Lichess TV ignores choice of game type

### ISSUE THREAD

**Issue by Manit100** [lichess-org/lichobile#1740]
**Describe the bug**
This bug relates to the Lichess TV section of the Lichess Android app.

**To Reproduce**
1. Go to the Lichess Android app
2. Choose "Lichess TV" from the hamburger menu on the left
3. Choose "Classical" or "Rapid" or "Crazyhouse" from the game type drop-down menu at the top
4. Note that you will probably be shown a Bullet or Blitz game instead

There is a small chance that you are actually shown a game of the correct type, but if you give it a couple of attempts, you will certainly be able to reproduce the problem.

**Expected behavior**
[Expected behaviour]
– When a user selects "Bullet", a Bullet game should be shown.
– When a user selects "Rapid", a Rapid game should be shown.
– When a user selects "Classical", a Classical game should be shown.
– (...and so on for all the 15 or so game types)

Considering the scale of Lichess, it should be very very rare that no game of a particular type is available to show on Lichess TV. And it should be almost impossible that no games of popular game types (such as Rapid and Classical) are available to show on Lichess TV.

--------

[Actual behaviour]
The Lichess Android app seems to default to showing the fastest (most restrictively time-controlled) game at that moment. Or, if this guess is incorrect, Lichess certainly seems to show the wrong game type very consistently. Regardless of the game type I choose from the drop down, I am usually shown a Bullet game (about 50% of the time) or a Blitz game (about 40% of the time). I am almost never shown a Classical game (0% of the time), even after I have explicitly chosen "Classical" from the Lichess TV drop-down menu. At the same instant, the Lichess TV section on the desktop website (accessed on a laptop or a desktop) continues to display games of all game types, respecting the user's choice of game type.

**Screenshots**
Not needed, kindly read the description.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - OS: Android 10, Android 11 (checked on both)
 - Browser: Lichess app
 - Version: Lichess app version 7.11.2 (always the latest version)
 --------
 - Device: OnePlus 6T
 - OS: Android 10, Android 11 (checked on both)
 - Browser: Lichess app
 - Version: Lichess app version 7.11.2 (always the latest version)

The same issue has been reproduced on at least 3 other Android phones.

**Additional context**
Within any game type (e.g.: "Rapid"), how Lichess determines which game to prioritise (a Rapid game between players A & B or a Rapid game between players P & Q) is not relevant to this bug. I presume that Lichess will choose to show the closest or the most highly-rated game. The point of this bug is that the user's choice in the drop-down is not being respected at all.

**Comment by jas14** [comment]
Thanks for the detailed report! I'm unfortunately unable to reproduce this. If you're still encountering this bug, would you mind providing, for each unexpected game type:

- the current time, including time zone, or UTC time
- the type of game you chose
- the game URL (can be obtained from the popup menu after clicking the bottom left menu button)

**Comment by Manit100** [comment]
**Current time**
1313h Indian Standard Time (UTC+0530)

**Type of game I chose:**
Rapid (and subsequently, Classical)

**What I was shown:**
Blitz (3+0)
Screenshot:
![Screenshot_20210630-131322](https://user-images.githubusercontent.com/62500480/123922532-c0a80480-d9a5-11eb-8333-2c623e82c430.png)

I was also shown Bullet (1+0) when the Blitz game was not in progress

**Game URL:**
(Bullet game) https://lichess.org/0f2QsSk7/white

**Device:**
Google Pixel 4a, with the phone OS and all apps completely up-to-date.
Have also reproduced this problem on three other Android phones (OnePlus 6T, Redmi Note 10, Samsung A52)


If I can put my point across another way: regardless of other preferences (show highest-rated game, show most recent game, show next game just about to begin, etc),  a user should always be shown a game of the type that he/she has chosen. So my understanding and hope is that there should never be a situation in which a user selects "Rapid" but it's shown "Bullet", regardless of whatever other preferences the user has chosen/set.

**Comment by Manit100** [comment]
Choice picked in drop-down menu:
Rapid

Game URL:
(Bullet) https://lichess.org/di1it6pj/white

Screenshot:
![Screenshot_20210630-132530](https://user-images.githubusercontent.com/62500480/123923625-ce11be80-d9a6-11eb-9d9d-051fa5c45b84.png)

Current time:
1325h IST (UTC+0530)

**Comment by Manit100** [comment]
Here's a suspicion: I think the drop-down is defaulting to the "Top-rated" option even if I have selected some other game type. That would explain:
— sometimes seeing Bullet and sometimes Blitz
— almost never seeing classical, because the highest rated players tend to prefer Bullet and Blitz
— the drop down showing "top rated" as selected even if I have chosen "Rapid"
![Screenshot_20210630-133136](https://user-images.githubusercontent.com/62500480/123924349-82abe000-d9a7-11eb-918d-c2b41fe0158a.png)

**Comment by jas14** [comment]
Thanks for the additional details - this clarifies things a lot. I'll look into this soon!

**Comment by Manit100** [comment]
I made a mistake. The problem _doesn't_ occur when I choose "Watch Lichess TV" from the hamburger menu. It occurs when I scroll down on the Lichess home screen and click on a live game. I do this by clicking on the live chess board, for example:
![Screenshot_20210705-161704](https://user-images.githubusercontent.com/62500480/124460390-f6395d00-ddac-11eb-95d4-a34b89424575.png)


That opens Lichess TV, and the UI works fine, except one item: the drop-down menu at the top that is supposed to change the game type (circled below).

![Screenshot_20210628-174801](https://user-images.githubusercontent.com/62500480/124460306-d5710780-ddac-11eb-9dfc-2fe4de37e87b.png)

**Comment by jas14** [comment]
That's extremely helpful - I think I've isolated the line just based on that description,

Technical notes: TV attrs from router clobber settings.tv.channel:
https://github.com/veloce/lichobile/blob/f7f9a63f396303b425648448263e6ff2a4c2faa5/src/ui/tv.ts#L27
