### ISSUE TITLE
Pawn Promotion Failure And Appropriation

### ISSUE THREAD

**Issue by GCD110** [lichess-org/lichobile#1775]
Of recent times when I engage in the playing of chess games, I've come across an issue that as to do with pawn promotion, whenever I want to promote a pawn, my screen freezes automatically, and takes the move back, making me play it several times, then without giving me an option to choose what piece I want, it gives me anyone usually the knight, this as led me loosing several games, even though I've got the advantage, and I noticed that it also occurs offline not only online, it's very frustrating, especially when you have the chance to win, or you had to make sacrifices to promote a pawn, and the end you can or you end up with a knight. Please this bug should be attended to urgently.

**To Reproduce**

**Expected behavior**
I expect the the piece options to show, so I can select the one I want, but it shows nothing, and in the end gives me a knight directly.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [ Lava Z92 ]
 - OS: []
 - Browser [lichess App]
 - Version [latest]

**Additional context**
Please this should be attended to urgently, thanks.

**Comment by jas14** [comment]
@GCD110 sorry for the trouble, it would be very helpful if you could provide a screen recording of this behavior. This may have some overlap with #1168 and might therefore be resolved by #1785 .

**Comment by jas14** [comment]
Assuming this is fixed, please let me know if the issue persists.
