### ISSUE TITLE
Dear Lichess! I can't rotate my phone while I'm playing, so a I can't see my partner, his rate, neither the time. I've got a Samsung Galaxy Fold 2. Would you help me? Thank you, your sincerely

### ISSUE THREAD

**Issue by Optimum1947** [lichess-org/lichobile#1872]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**
Dear Lichess! I can't rotate my phone while I'm playing, so a I can't see my partner, his rate, neither the time. I've got a Samsung Galaxy Fold 2. Would you help me? Thank you, your sincerely

**Comment by jas14** [comment]
Duplicate of #1635
