### ISSUE TITLE
I cannot find any games. Opponent or me always grey

### ISSUE THREAD

**Issue by theoriginalirontriangle** [lichess-org/lichobile#1937]
I have been playing lichess for a while but recently every match I join the opponent is grey or I am showing grey. The match always aborts.

I have tried all the basic troubleshooting and I cannot figure out what the issue is. I am playing anonymously.

thanks

**Comment by jas14** [comment]
@theoriginalirontriangle please fill out the entire issue template, including and especially device info (make and model) and the app verison. I suspect you're on iOS, as multiple iOS 15 upgrade issues (see #1898) were reported at around this time.
