### ISSUE TITLE
Patron wing isn’t showed in timeline

### ISSUE THREAD

**Issue by Baikalcadillac** [lichess-org/lichobile#1960]
![FD79092B-6145-4326-9C64-F06B6107187D](https://user-images.githubusercontent.com/67504540/147220577-46594569-8586-4e56-b21d-cb2da16f4e09.jpeg)

**Comment by jas14** [comment]
@Baikalcadillac thanks for the report - would you mind posting a screenshot of the relevant parts of your timeline as seen on the desktop app, for reference?

**Comment by Baikalcadillac** [comment]
Yes, here is how it looks in mobile browser. 

![72CC08B1-6A7F-47B0-B61E-732115267455](https://user-images.githubusercontent.com/67504540/147286505-0b2d6997-cc83-4701-83be-f2d6e3f67613.jpeg)

**Comment by jas14** [comment]
Server code is deployed 🎉
