### ISSUE TITLE
"Track your progress" window an unregistered user on Android app has invalid description

### ISSUE THREAD

**Issue by wojtekweg** [lichess-org/lichobile#1985]
**Describe the bug**
The application is showing the "track your progress" window in a weird way for an unregistered user by displaying the text "toTrackYourProgress". This happens on a "puzzle page" on an Android app. The information shouldn't look like a function name, but should have text about required login to display the progress.

**To Reproduce**
Steps to reproduce the behaviour:
1. Logout from the app
2. Go to puzzle page
3. Click track progress icon (the one with the diagram)

**Expected behaviour**
Clear and nice information about required login should be displayed.

**Screenshots**
![Screenshot_20220116-000311_lichess](https://user-images.githubusercontent.com/49337058/149674915-1a902088-5092-41da-a164-9db801b47d1e.jpeg)

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android 11
 - Lichess app of version 7.13.1

**Comment by wojtekweg** [comment]
This issue looks similar to https://github.com/veloce/lichobile/issues/1469

**Comment by jas14** [comment]
Looks like this translation key was lost in fd744add97466ec0b8d5e9aff58da4b3b39fc44e. IIRC it was around that time that the puzzle rating graph was removed from the app. I suggest we just not show the graph button for logged-out users. I'll open a PR for that.
