### ISSUE TITLE
Tablebase display uses figurine notation regardless of preferente

### ISSUE THREAD

**Issue by djpohly** [lichess-org/lichobile#1990]
**Describe the bug**
When the opening explorer displays tablebase information, the letter notation preference is ignored. Moves are always displayed with figurines.

**To Reproduce**
1. Go to Settings/Game display and set Move notation to Letter.
2. Load an analysis board or study with only a few pieces on the board (e.g. [this one](https://lichess.org/study/QeYVz0jx/PNuEifY0)).
3. Switch to the explorer tab to see tablebase information.

**Expected behavior**
Moves are shown in letter notation.

**Actual behavior**
Moves are shown in figurine notation.

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 11
 - Default browser: Firefox
 - App version: 7.14.1

**Comment by jas14** [comment]
Can reproduce on OnePlus 6, Android 11, 7.14.1.

**Comment by jas14** [comment]
Looks like the tablebase piece notation is lazily loaded on first render, so it won't change until this module is reloaded (app switch/quit?)

https://github.com/lichess-org/lichobile/blob/b25506f6cc2c16480ac993da337c56960a67e439/src/ui/analyse/explorer/OpeningTable.tsx#L149

**Comment by jas14** [comment]
Actually, this is true all over the codebase, at least for this setting.
