### ISSUE TITLE
Text readability in studies and move history.

### ISSUE THREAD

**Issue by 2i3r** [lichess-org/lichobile#1993]
**Is your feature request related to a problem? Please describe.**
Reading through studies (comments)/game moves, is hard, as readability is pretty low. font size is monotone, new line on most of studies doesn't work,  and there is not much text format. 

**Describe the solution you'd like**
Adding support for markdown styling, font size settings, and replacing incompatible new line/return carriage, should resolve problem.

**Describe alternatives you've considered**
font size settings alone might help a lot. 

**Additional context**

![edited2](https://user-images.githubusercontent.com/16647235/149787299-2b666129-5769-4945-9ecf-8035918f7c14.jpg)

**Comment by veloce** [comment]
Closing as new lines have been implemented.
