### ISSUE TITLE
re-color arena result colors

### ISSUE THREAD

**Issue by ornicar** [lichess-org/lichobile#1994]
due to a change in the arena network representation of scores, the app now needs to compute the right color (normal, streak, double) for scores on a player details panel

![](https://i.imgur.com/Zlsv8fZ.png)

Example implementation: https://github.com/ornicar/lila/commit/7780571ffddd8a2f3a26b9460f7818185879b75d#diff-b7046f9bcbd2057a10cf33a05a9e1736bca5728302236c9c1d99cc9a2100f06dR10

Scores used to be either a number or an array of [value, color], now it's just numbers.

Not a big deal, nothing is too broken, just a bit less pretty.

**Comment by veloce** [comment]
@ornicar while on it I noticed that some tournaments have an option "non streakable"; it looks like this field is absent from tournament json in mobile api, it would be nice to add it so the app render score correctly for those tournaments.
