### ISSUE TITLE
Showing threats.

### ISSUE THREAD

**Issue by shah-xad** [lichess-org/lichobile#2005]
It would be great if the showing threats feature would be implemented in the app as it's available on the website.

![Screenshot from 2022-01-24 22-07-32](https://user-images.githubusercontent.com/32363363/150830465-12336708-7321-47b5-bf79-cce6b4d6f989.png)

**Comment by surfstian** [comment]
Wut? There is a showing threats function?  Isn't that 'forbidden word'?  

I'm confused.
