### ISSUE TITLE
Unlock 120hz framerate on iPad Pro

### ISSUE THREAD

**Issue by bostoys** [lichess-org/lichobile#2006]
**Is your feature request related to a problem? Please describe.**
The Lichess mobile app on new iPad Pro doesn't play at 120hz. It seems to be 60hz capped where the rest of the apps on the iPad Pro are working at 120 hz. The Lichess.org website in Safari and Chrome are also playing at 60hz. 

**Describe the solution you'd like**
I would like the Lichess app to be able to be played at 120 hz.

**Comment by jas14** [comment]
Safari [does not support 120hz](https://bugs.webkit.org/show_bug.cgi?id=173434). This app is powered by a browser, so there's unfortunately nothing we can do about it, but it will naturally resolve itself once Apple enables 120hz.

That being said, the maintainer (veloce) [has been hired by Lichess](https://lichess.org/blog/Y2Z47hEAAGUB7i7A/lichess-recruits-full-time-mobile-developer) and is now working full-time on an app rewrite, which will be written in Flutter, which [does support ProMotion](https://github.com/flutter/flutter/issues/90675#issuecomment-1082421062).
