### ISSUE TITLE
Bug lichess

### ISSUE THREAD

**Issue by RHKJACOBS** [lichess-org/lichobile#2018]
**Describe the bug**
While playing chess Lichess page go on black screen. After short flikkering screen. 
can’t refresh or enter in game again. 
happend two times in three games. Game lost because of leaving………

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPad 2 6e generation 
 - OS: [e.g. iOS14.8.1
 - lichess app
 - Version up to date. 

**Additional context**

**Comment by veloce** [comment]
Closing due to insufficient information/context to handle this.

**Comment by RHKJACOBS** [comment]
Oké, can’t give more info because there isn’t. App kust starts to flicker
SER white screen, than complete black screen. And no option to get back to
the game.
Sorry what do you want to know more it happened two times in a row within 5
minutes.
I feel bad about it because it looks if I have abandoned the game but I
didn’t.
So I thought I’ll report it.
Bye 👋

Op vr 11 feb. 2022 om 10:23 schreef Vincent Velociter <
***@***.***>
