### ISSUE TITLE
Chess Clock: Showing no. of moves

### ISSUE THREAD

**Issue by susmitpy** [lichess-org/lichobile#2024]
**Is your feature request related to a problem? Please describe.**
When playing on physical board and using chess clock feature in the mobile app, there is a need to know the no. of moves played so far

**Describe the solution you'd like**
Keep a move counter initialised to 0
On every tap (either side) increment it by 0.5
A getter can be made for display: current no. of moves, which floors the move counter and returns the integer.
The flow:
_________________
Move counter: 0
Getter returns: 0
White taps
_________________
Move counter: 0.5
Getter returns: floor(0.5) = 0
Black taps
_________________
Move counter: 1.0
Getter returns: floor(1) = 1

**Additional context**
It can be shown either besides the centre buttons or as a floating badge besides the centre buttons

**Comment by veloce** [comment]
I'll see if I have the time, in the meantime PR would be accepted!

**Comment by jas14** [comment]
Complete!
