### ISSUE TITLE
Lag on my account is horrid

### ISSUE THREAD

**Issue by Eggandk** [lichess-org/lichobile#2037]
**Describe the bug*
The lag is horrid I have lost soo many games recently due to that, it is taking my time for the other player to think on their moves, also I have lost a game the last one, it showed that the other player was not making a move and run out of time and I run out of time, where I made my move soooo quickly, that is the last one, the other games today I was stressing focusing too much on the lag that I couldn’t not focus on the games, the comment you have on compensation is super false, look at the last game, I have full time very little time used, and the time running out on the other player supposedly was mine after his time run out, my internet is flawless, I want those games rating back or fix it please. It is not fund dealing with this.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by veloce** [comment]
GitHub is about contributing to make the software better. Not about complaining, sorry but you have other channels for this.

**Comment by Eggandk** [comment]
I tried to reach out to you, could not find the way, it sent me here. I
will delete my comment, I don’t think you realized that there is no option
to ask for help.

**Comment by veloce** [comment]
There are options to ask for help. If you want to improve this app you can do report bugs here, but it require a little effort so the report is actually useful. See https://github.com/lichess-org/lichobile/blob/8889a684b919ffbd425e5ac840e9074c2efc06f8/CONTRIBUTING.md

**Comment by Eggandk** [comment]
Got it, thank you for the guidance!
