### ISSUE TITLE
Analysis board is showing the evaluation for the worst line, instead of the best

### ISSUE THREAD

**Issue by xAptive** [lichess-org/lichobile#2045]
The analysis board on the app is showing the evaluation for the worst line calculated, instead of the best line calculated.  This occurs on the "opening explorer" and "moves played" windows.  The evaluations on the stockfish page are correct.  I do not believe this is a stockfish problem, but rather a problem with the code that displays those results.

For example, in the attached stockfish.png, you can see a position where it is black to move, and the best move calculated is 4...Qxc7, which is evaluated as -10.8.  There is also 4...Nxe4 which is +2.6, and finally 4...O-O which is +3.7.  The opening explorer should consider this position as -10.8, which is what it would be if black made the best move.  But instead, it is evaluated as +3.7, which is what it would be if black made the worst move calculated.  (See the attached bad_eval.png.)

So again, the problem isn't with stockfish.  The stockfish page looks right.  But the opening explorer and moves played pages are showing the wrong value from the stockfish output.

Also, I just verified this only happens when not using the cloud evaluations.  So really this will be most likely to occur in less popular and deeper positions.

To reproduce this bug:
1. Open the analysis board
2. Ensure that multiple lines are being calculated
3. Make a series of moves that lead to a sharp position.  For example, one where the queen is hanging.
4. Make sure it's a position that hasn't been reached before so that it's not in a cloud evaluation database
5. View the stockfish evaluations and see that they look correct
6. Go to the openings database page and see that it's using the worst evaluation, not the best
7. Go to the "moves played" page and see that it's using the worst evaluation, not the best

 - Device: Pixel 4
 - OS: Android 12
 - Lichess Version: 7.15.0

This started occurring roughly 1 week ago, and has been a consistent problem since then.

![stockfish](https://user-images.githubusercontent.com/39704195/156650028-629ce404-f30d-461c-984f-b3c8fd942e93.png)
![bad_eval](https://user-images.githubusercontent.com/39704195/156650032-2a964009-b4f7-43f4-b73e-9e5f10bded12.png)

**Comment by veloce** [comment]
Thanks for the report, will fix asap.

**Comment by xAptive** [comment]
Thanks for the amazingly fast fix!
