### ISSUE TITLE
https://lichess.org/hbPVE0WO/white#59

### ISSUE THREAD

**Issue by Talga195** [lichess-org/lichobile#2065]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Talga195** [comment]
Why did the cancellation come out at the end of the game on the smartphone?

**Comment by veloce** [comment]
Issue was closed because it does not respect contributing guidelines: https://github.com/lichess-org/lichobile/blob/master/CONTRIBUTING.md
