### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sehzade87** [lichess-org/lichobile#2066]
![Screenshot_20220318-224421_lichess](https://user-images.githubusercontent.com/19703756/159077260-f4a2e484-9c91-462e-b996-8e49ffd8f5ec.jpg)
![Screenshot_20220318-224411_lichess](https://user-images.githubusercontent.com/19703756/159077266-bce6db3d-4ab5-4e78-a3da-6b79fe373640.jpg)

**Comment by jas14** [comment]
This is called en passant, it's a rule of chess, not a bug :)

**Comment by sehzade87** [comment]
replace image. white pawn e5 move d6 and d5 Black pawn lose. this isnt rule.

**Comment by sehzade87** [comment]
sory.  ok
