### ISSUE TITLE
Castling is possible even when path is cut off

### ISSUE THREAD

**Issue by Lindanib** [lichess-org/lichobile#2069]
**Describe the bug**
You can castle even though the path to castling might be blocked by an opponents piece's attacking path. 

**To Reproduce**
1. Start a game
2. Play a game and get to a position where you need to castle but your opponent has placed a piece(eg bishop) on a line that will stop the possibility of castling
3. Try castling anyways 

**Expected behavior**
Should not be able to castle

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 8
 - OS: Android 10
 - Lichess App (play store)
 - Version 7.15.1

**Additional context**

**Comment by jas14** [comment]
Please provide a link to a game where this happened so we can verify the issue :) this has been reported previously for games where castling was in fact legal.

**Comment by Lindanib** [comment]
It was a blitz game, which I didn't really pay much attention to. I was unable to reproduce the error. You can close this
