### ISSUE TITLE
Pre-move capture not cancelled when target piece was moved

### ISSUE THREAD

**Issue by CS22** [lichess-org/lichobile#2084]
https://lichess.org/xHRZpCRh/black

`33. ... Nc7`

was a pre-move to capture the rook (target square was blue etc); when the rook moved on white's turn, the knight immediately moved to the square the rook was last in.

From experience aren't pre-move captures cancelled if the capture becomes impossible? 

Android v7.15.1

ONEPLUS A3003_16_191104
Android ver. 9
OxygenOS ver. 9.0.6

**Comment by CS22** [comment]
The pre-move was set for at least a couple of seconds.

**Comment by jas14** [comment]
This is intentionally how premoves work: they're always executed unless the game has ended or the move is or becomes otherwise illegal. The idea is that the player may deliberately trade accuracy for time.

**Comment by CS22** [comment]
Ah I see, thank you for clearing that up. I must've been extrapolating from re-captures and pawn captures, both of which would be cancelled if the opponent didn't move as expected. Just amazed I've not encountered this yet in 200+ hours on Lichess!

Has it always worked like this and at all time controls?

**Comment by jas14** [comment]
I believe so – I'd have to look at the version history, but I don't think the code powering the chess board has changed much.

**Comment by CS22** [comment]
Ok great, thanks for your help!
