### ISSUE TITLE
VIBRATION during gameplay is weaker on some androids

### ISSUE THREAD

**Issue by carlosaandres** [lichess-org/lichobile#2095]
hello there!

I'd like to report some odd behavior about the vibration in some android devices:
usually when a player or the opponent makes a move, there is an option to vibrate
on game events like these. And this is a good thing, giving a tactile feedback when holding the cellphone.

However, there's been a subtle change in the vibration for some android devices, or other devices as well during a game,
every move made, the device vibrates in a very weak way, which is odd and doesn't feel nice.
Actually, it doesn't feel anything at all, what may cause some trouble when playing outside on public transports and related situations when we might loose the attention for the game for a few seconds.

It would be nice to test this issue and if possible fix it. Also, having a strengh bar for the vibration would be a welcome plus to this feature, since some players might like it weaker or stronger than others. I'm saying that as a player and professional game designer.
Thank you guys for the awesome work!!

**Describe the bug**
When playing with the "vibrate on game events" active,
the vibrations seem weaker than before in some devices.

**To Reproduce**
1. Go to 'options'
2. Click on 'vibrate on game events'

**Expected behavior**
The vibrations should be strong enought to feel them in your hand.
And long enough to have the proper feedback.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
_**Where the vibration is still normal:**_ 
- Device: Multilaser F 
 - OS: Android 10
 - Version (Build Number) ML-TI-MSF.V4_20210518
 - Lichess Version: 7.15.1

_**Where the vibration is weaker:**_ 
- Device: Asus Zenphone ASUS_A001D
 - OS: Android 9
 - Version (Build Number) WW_Phone-16.14.2009.319_20200825
 - Lichess Version: 7.15.2

**Additional context**
These are the only phones I had to test the issue with, I hope it helps.

**Comment by jas14** [comment]
@carlosaandres there was [recently](https://github.com/lichess-org/lichobile/releases/tag/v7.15.2) a [change](https://github.com/lichess-org/lichobile/pull/2079) to the haptic feedback code. Can you please fill out the issue template, including/especially your device make & model and the version of Lichess you're on?

**Comment by carlosaandres** [comment]
@jas14 of course! will do

**Comment by carlosaandres** [comment]
@jas14 DONE!

**Comment by veloce** [comment]
This change was made on purpose so devices that do not have an haptic engine can also distinguish between a move and a capture or a check for instance. So to me it's an improvement.
The vibration is weaker but still largely perceptible, it's just a matter of getting used to it.
