### ISSUE TITLE
Special character in inbox chat breaks android rendering, resulting in unusability

### ISSUE THREAD

**Issue by schlawg** [lichess-org/lichobile#2108]
Originally I had this character in the issue, U+1160 : HANGUL JUNGSEONG FILLER

We could always filter it, but doubt we can fix completely as it seems to be out of our hands.

On TheChessGuy2_0's device (and I suspect many others) - when that character is typed or received in inbox chat using mobile browser or lichess app, it causes the inbox display to expand horizontally placing the other user's chat bubbles and the send button offscreen.

If this is not isolated to just the reporting user's device profile and it also occurs in other chat views, I worry this could be posted in a tournament chat and blow it up for android users.  Reporting user's device profile is https://www.whatismybrowser.com/w/8BCMQ64

His thread on feedback forum is https://lichess.org/forum/lichess-feedback/inbox-bug-2

**Comment by jas14** [comment]
FWIW this similarly breaks my GMail inbox rendering and GitHub's mobile rendering on my OnePlus 6. Seems like an Android WebView problem.

**Comment by schlawg** [comment]
I should probably remove it from the issue.
