### ISSUE TITLE
Disable swiping action during a match

### ISSUE THREAD

**Issue by biergit** [lichess-org/lichobile#2114]
**Is your feature request related to a problem? Please describe.**
On a Pixel phone playing blitz games is hardly possible because of the annoying swipe action that triggers whenever you move a piece from the a or h lines unless you are veeeery precise.

**Describe the solution you'd like**
Best option: Remove the swipe action.
Second best: Provide a setting to allow to disable it.

**Comment by jas14** [comment]
Duplicate of #1027
