### ISSUE TITLE
Mobile app issue

### ISSUE THREAD

**Issue by starcreative2019** [lichess-org/lichobile#2115]
I cant play online in mobile app 
![F586DAFC-D3B5-4373-B610-71363B60DF64](https://user-images.githubusercontent.com/106149843/169998809-189755a6-f780-4232-b69b-e4d5c3c51f91.png)

**Comment by starcreative2019** [comment]
There is no play online option 
And no lobu option in mobile app

**Comment by jas14** [comment]
All of the 9 buttons on the home screen - 1+0, 2+1, 3+0, etcetera - are for playing online. So are the "play with a friend" and "create a game" buttons.

As for the lobby, see #1149
