### ISSUE TITLE
Add a notification for running out of time correspondence match

### ISSUE THREAD

**Issue by mesk421** [lichess-org/lichobile#2116]
Hi,
Is it possible to add a feature for the mobile app to notify when you are running out of time during a Correspondence match?
Something like "The match will be over in 4 hours" or something like that.

Thanks!

**Comment by jas14** [comment]
Push notifications are implemented on and sent by the lichess server. I believe this notification already exists, but if it's not working for you, please search https://github.com/lichess-org/lila or [the Lichess discord](https://discord.com/invite/lichess) for similar issues.
