### ISSUE TITLE
I can not see the messages my opponent sends. I see notifications but when I check inbox there are no messages. I use iOS 15. When I reply I see my messages. This situation has been happening for one or two months

### ISSUE THREAD

**Issue by kodcuserkan** [lichess-org/lichobile#2134]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by veloce** [comment]
Cannot reproduce on iOS 15 (and issue does not respect template).
