### ISSUE TITLE
Custom lobbies

### ISSUE THREAD

**Issue by DScottArch** [lichess-org/lichobile#2136]
**Is your feature request related to a problem? Please describe.**

Unable to see lobby for custom games.

**Describe the solution you'd like**

I'd like to be able to have the lobby for custom games shown. Right now, there's only the ability to create custom games on mobile, but there's no lobby to select custom games to join. 

**Describe alternatives you've considered**

Custom lobbies are only available on the web version.

**Additional context**

None.

**Comment by jas14** [comment]
Thanks for the details @DScottArch. This was already requested as #1149, please give that issue a thumbs up so we can continue to gauge interest.
