### ISSUE TITLE
Swiss tournament link on iOS not opened in the app

### ISSUE THREAD

**Issue by Azhy-Slemany** [lichess-org/lichobile#2147]
When I open the swiss tournament links made by someone else, it doesn't have an option to open in the app, and it immediately opens the browser, so I searched in the associated links in the iOS folder, that it doesn't include swiss path after the lichess.org/ links, and I think this made the problem, thanks in advance.

**Comment by jas14** [comment]
Duplicate of #1348

**Comment by jas14** [comment]
This feature isn't implemented on mobile (yet) — please give #1348 a thumbs up so we can gauge interest. Thanks!
