### ISSUE TITLE
I won a game on time and one move away from mate but Lichess site froze and aborted the game

### ISSUE THREAD

**Issue by Aezen23** [lichess-org/lichobile#2149]
**Describe the bug**

I won a game on time and one move away from mate but Lichess site froze and aborted the game.

**Expected behavior**

I want the rating points! I was playing nimiord, my handle is Aezen23.

**Screenshots**
![image](https://user-images.githubusercontent.com/109605319/179767874-f4bc59f8-4b77-4f74-bbfc-96551a8cca3a.png)

You can clearly see the white king is in check and has only 1 legal move, Kh1 with Qg2 mate.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 15.5

**Comment by FreshMedlar** [comment]
Same thing. The game aborted the moment my opponent loses on time

**Comment by jas14** [comment]
I think these were both likely due to a server crash. See https://github.com/lichess-org/lichobile/issues/2268#issuecomment-1353395656 . Going to close until this appears again without a server issue.
