### ISSUE TITLE
When I listen to music, I go to the app! The music stops

### ISSUE THREAD

**Issue by harryhole13** [lichess-org/lichobile#2157]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

When I listen to music, I go to the app! The music stops

**Comment by photon-e** [comment]
please describe the bug better by filling out the form appropriately. it helsp provide steps to reproduce the bug

**Comment by jas14** [comment]
Duplicate of #1917
