### ISSUE TITLE
Chess board view on Galaxy Z Fold 3

### ISSUE THREAD

**Issue by fizikci** [lichess-org/lichobile#2165]
Time dissappears. Text is cut. Screenshot attached.
![SmartSelect_20220812-083904_lichess](https://user-images.githubusercontent.com/763066/184391764-6fc1519a-32c4-4d18-a39b-224069df2167.jpg)

**Comment by jas14** [comment]
Duplicate of #1635 , please react w/a thumbs up to that issue to indicate you're also affected
