### ISSUE TITLE
Lichess 

### ISSUE THREAD

**Issue by Rondy177** [lichess-org/lichobile#2171]
Beim Versuch, einen Bauern auf der 8. Reihe umzuwandeln, erscheint ein großes weißes Feld, auf dem ich nichts anklicken kann. Die Zeit läuft weiter bis zum Ende, ich verliere die Partie. 
Erwarten würde ich, wie es bis vor 2 Wochen auch noch war, ein weißes Feld, auf dem die möglichen Umwandlungsfiguren Dame, Turm, Springer und Läufer abgebildet sind und ich kann eine Figur wählen, dann geht das Spiel weiter.  **Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Rondy177** [comment]
Gerät, 
Mi pad 4 plus

**Comment by jas14** [comment]
Duplicate of #2170
