### ISSUE TITLE
Zero time left for both players

### ISSUE THREAD

**Issue by bvbeek** [lichess-org/lichobile#2173]
Safari on iPhone XS Max iOS 15.6.1

![7262D448-01C2-470E-874B-D850C3393DCA](https://user-images.githubusercontent.com/28626283/185553689-d7373e02-81b0-42d4-91e7-aee6bd0d2938.jpeg)

**Comment by jas14** [comment]
@bvbeek the screenshot you attached is not of the Lichess mobile app, but rather of the Lichess website. The website repository is https://github.com/lichess-org/lila - please check out the help resources over there. Thanks!
