### ISSUE TITLE
Rating bug

### ISSUE THREAD

**Issue by nyborhteb** [lichess-org/lichobile#2181]
**Describe the bug**
Hi, I just played a rated rapid game on lichess (like I do every night) and for some reason no points were awarded. I triple checked it was a rated (not casual) game before asking, and also that I wasn't playin against a bug.

The only reason I am here is because I want to make sure it's not recurring. Can you please help? 

Btw my name lichess name is nyborazile 

**To Reproduce**
You'd have to play another game.

**Expected behavior**
+ or - when you win or lose a rated game as expected

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iphone11

**Additional context**

**Comment by jas14** [comment]
Lichess [uses the Glicko-2 rating system](https://lichess.org/faq#ratings). There are certain conditions under which games you win may not award you points, and conversely, under which games you lose may not detract from your rating.

In any case, this is entirely server controlled. Please see GitHub.com/lichess-org/lila if you still believe there is an issue.
