### ISSUE TITLE
Can't convert pawn

### ISSUE THREAD

**Issue by Matzthias** [lichess-org/lichobile#2190]
Hello guys I have this problem from time to time that I can't convert my pawns. I had this like 5 times now I'm very confused.
Playing on Android
I lost the game because of that... 
![Screenshot_20220911-215603](https://user-images.githubusercontent.com/113310960/189546919-0c8ed444-6269-47c9-baac-df36933d3243.jpg)

**Comment by jas14** [comment]
Duplicate of #1793.

@Matzthias , this unfortunately has been a common report since 7.16.0. Please comment on #1793 with more information (at least OS and device make & model), that will be very helpful. Thanks

**Comment by Matzthias** [comment]
Android 8.0. I think it's an huawei p8 lite (WAS-TL10)
