### ISSUE TITLE
Playing against computer (stockfish level 3) and the opponent starts to play with my pieces.

### ISSUE THREAD

**Issue by NoudL** [lichess-org/lichobile#2195]
I was playing against stockfish level 3 and after castling as white, the computer played my pieces instead of a black piece.

**To Reproduce**
1. Play against stockfish 3 on Android ( OnePlus Nord2 )
2. Castle (?)
3. The CPU plays my piece instead

**Expected behavior**
That the CPU only plays their pieces. 

**Screenshots**

https://user-images.githubusercontent.com/42575107/190924795-cc8f3c23-9b60-465d-b401-edfc1b4db374.mp4

**Smartphone (please complete the following information):**
 - Device:  OnePlus Nord2
 - OS: Android 11
 - Version Android App 7.16.0

**Comment by jas14** [comment]
Duplicate of #1637.
