### ISSUE TITLE
Link to play guest player

### ISSUE THREAD

**Issue by rajsinghUSA** [lichess-org/lichobile#2205]
You should be able to create a game with a link that you send to someone who can join as a guest player (not logged in). This feature does not appear to exist on the Android app.

**Comment by jas14** [comment]
@rajsinghUSA , @mikusHusbando's explanation is correct, this issue already exists. If that's not what you meant, please feel free to comment, but in the meantime, I'm closing this issue as resolved.

**Comment by rajsinghUSA** [comment]
Ahh, thank you! I think it would be very useful to have this in the hamburger menu as well.
