### ISSUE TITLE
<iframe> text renders in activity layout

### ISSUE THREAD

**Issue by jalpp** [lichess-org/lichobile#2212]
**Describe the bug**
some one wrote <iframe> in forum post as a text but it rendered on mobile app 
**To Reproduce**
1. go to this forum post 

https://lichess.org/forum/lichess-feedback/problems-including-iframe-in-my-website#2

follow someone who commented on forum 

See the person's activity on mobile Home Screen and you will see a big white block 
**Expected behavior**

Just see the normal activity layout not a white block ![image](https://user-images.githubusercontent.com/92553013/194764465-d07ce16e-dbf0-4a52-a6f2-e4e741d56664.jpeg)
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone10]
 - OS: [e.g. iOS15]
 

**Additional context**

**Comment by niklasf** [comment]
Thanks for reporting. Since this is a security issue, we have disabled the timeline on mobile until this can be fixed properly.
