### ISSUE TITLE
I have disabled pre-moves but my opponent is still doing it 

### ISSUE THREAD

**Issue by dsglobal1** [lichess-org/lichobile#2213]
I’m playing multiple games (1 min rapid) that don’t appear fair. My opponents are getting 5,6,7 moves in without it counting against their clock even though I’ve already disabled pre-moves in my settings. Does this only apply to me? Is it possible to disallow that for both players? Can anyone help?

**Comment by jas14** [comment]
@dsglobal1 , the premove setting is for your side of the game only. It's for those who don't prefer to use the feature. There is no way to turn it off for opponents.
