### ISSUE TITLE
Unequal points given/taken after games end?

### ISSUE THREAD

**Issue by dsglobal1** [lichess-org/lichobile#2218]
**Describe the bug**
I often play 1-minute bullet/speed chess. When the game ends, I often notice a difference btwn the points that either I or another person is rewarded or penalized. Why would I be rewarded 15 points, as just an example, as my opponent loses only 5 points? Or vice versa? Does anyone know?

**To Reproduce**
Choose any 1 min bullet game. At the end, this issue appears.

**Expected behavior**
I expect both sides to win/lose the same amount of points when a game ends unless point are being awarded (or lost) for strategy, win/lose streak, piece value, etc? Can anyone advise?

**Screenshots**
Attached.

**Smartphone (please complete the following information):**
 - iPhone 12 Pro, using LiChess app.

**Additional context**
N/a
![325C7D5D-AF65-4851-83B9-163F9C2EEC05](https://user-images.githubusercontent.com/115515753/196037269-dad3d598-7660-483d-b1e4-af6209ba9a21.jpeg)

**Comment by jas14** [comment]
Lichess uses the Glicko 2 rating system. See https://github.com/lichess-org/lichobile/issues/2181#issuecomment-1239350637 for a slightly more detailed explanation.

**Comment by dsglobal1** [comment]
Wow @ the speed of this reply. Thank you! Will review. Much appreciated.
