### ISSUE TITLE
Keepass2Android Reports Security Alert

### ISSUE THREAD

**Issue by redyoshi49q** [lichess-org/lichobile#2235]
When using Keepass2Android to authenticate with lichess.net using the Lichess Android app, a security alert is generated:

![Screenshot_20221104-134134_Keepass2Android](https://user-images.githubusercontent.com/3804316/200069258-4a1f760f-1e01-490d-af1e-d47654e70a41.jpg)

I suspect that this might be happening because the Lichess app is operating as a locally hosted proxy server under the hood.  This error might be concerning to some Keepass2Android users, though, so the use of an authentication means that wouldn't produce this alert (perhaps Oauth?) might be warranted.

(For the sake of making search engines able to find this issue report, the error message's text is quoted below:

> Security Alert: Unrecognized domain/app link
> 
> You are about to insert credentials for domain localhost into the app lichess (org.lichess.mobileapp). If you trust lichess to belong to localhost or you trust the app lichess not to misuse the credentials (e.g. because it is a trusted browser app), it is ok to continue. If not, please cancel.

)

**Comment by jas14** [comment]
First of all, thanks for the detailed report. (Second of all, excellent default font face. 😉)

You're right that the local scheme/host are by default http://localhost. This is how Capacitor works; it's fundamentally built on a Webview, and I'm not sure it's safe to change the host/scheme at this point for compatibility reasons.

Fortunately, veloce is working on a full rewrite of the app in Flutter, which I don't think will have this problem. The first build probably won't be out until some time in the first half of 2023.
