### ISSUE TITLE
App won't display pieces icons when pawn reaches 8th row

### ISSUE THREAD

**Issue by lesanges** [lichess-org/lichobile#2237]
**App won't display pieces icons when pawn reaches 8th row**
When trying to solve problem #219877472 (https://lichess.org/training/0Kk2O), I play f7-f8 ; instead of displaying the icons of the pieces to let me choose the promotion I want, the app only displays a semi-transparent rectangle and I can't neither choose a piece to promote the pawn to, nor do anything except hit the back button.

**To Reproduce**
Well, I don't know how to select a specific problem on the mobile app ; this is what I did several times, while that specific problem whas proposed to me :
1. Go to app home page
2. Scroll down to day problem 
3. Click on the problem chessboard
4. Move  white f7 pawn to f8

**Expected behavior**
I expect the app to display the icons of the pieces to let me choose the promotion I want, as it does on the web client and go on playing.

**Screenshots**
[Screenshot_20221108-090855_lichess](https://user-images.githubusercontent.com/104074027/200679787-c5873562-7bf7-4c2d-834d-695cecfdcf9b.jpg)

**Smartphone:**
 - Device: Samsung Galaxy A5
 - OS: Android 8.0.0
 - Browser: ?
 - Version: 7.16.0

**Comment by jas14** [comment]
This has been reported fixed for most users as of version 7.16.1 🎉  Please upgrade to the latest app version and write back here if the problem persists.

**Comment by igoose1** [comment]
v. 8.0.0 (github releases and f-droid): got the same bug. Downgraded to v. 7.16.1 and v. 7.16.0 of f-droid: all of them are broken too.

How can I help to give more information?
