### ISSUE TITLE
Typo in about page

### ISSUE THREAD

**Issue by Matthew-Tyrone-Campbell** [lichess-org/lichobile#2239]
On the about page there is a typo reading: lichess would not exist without the thousands of hours of time from volunteers, both from website devs and mobile devs, who create new features and/or bugs.

**Comment by jas14** [comment]
@Matthew-Tyrone-Campbell I can't tell at first glance what the issue is here, please highlight the typo and what correction needs to be made

**Comment by Matthew-Tyrone-Campbell** [comment]
create new features and/or bugs.

**Comment by jas14** [comment]
I think the "and/or bugs" is meant to be funny. 😉

**Comment by Matthew-Tyrone-Campbell** [comment]
🤣

**Comment by Matthew-Tyrone-Campbell** [comment]
I like it

**Comment by jas14** [comment]
Excellent — in that case I'll close the issue
