### ISSUE TITLE
Analysis graph not rendering properly

### ISSUE THREAD

**Issue by dvalenca** [lichess-org/lichobile#2249]
**Describe the bug**
When analyzing a game, the graph shows both white and black curves.

**To Reproduce**
1. Go to a game you played
2. Click on analyse
3. Click on graph

**Expected behavior**
A graph oscillating between black and white, with a single line, showing which has advantage at a certain point of the game

**Screenshots**

![Screenshot_20221201-141603_lichess](https://user-images.githubusercontent.com/19825153/205118829-f0411852-5a18-4646-a43b-2bbb8d44910f.jpg)
![Screenshot_20221201-141512_lichess](https://user-images.githubusercontent.com/19825153/205118838-0c497c39-7489-4006-b5fc-5c95c89c23f6.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy A13
 - OS: Android 12
 - lichess app
 - Version 7.16.1

**Additional context**
A proper graph
![Screenshot_20221201-142656_Chess](https://user-images.githubusercontent.com/19825153/205120085-b6f465f0-b2f8-4d75-8acc-141d1ff939ab.jpg)

**Comment by jas14** [comment]
@dvalenca per the title of the graph, you are looking at the "time per move" / "tempo por movimento." You have to click "request a computer analysis" button to see the advantage graph.

**Comment by dvalenca** [comment]
Yeap. I came here to say i'm dumb. :( 
Sorry
