### ISSUE TITLE
New game never found on mobile

### ISSUE THREAD

**Issue by SedNomini** [lichess-org/lichobile#2262]
If I’m using an internet client (safari,chrome) on mobile, the quick match finds a game in a matter of seconds regardless of the time control. But if I use the app, the searching for game window comes up, it shows how many are currently playing, but then it never connects me to a game. This means I have to play all my games on an internet client, and at that point, why even have an app?

**Comment by jas14** [comment]
@SedNomini please fill out the entire issue template, including:

* phone make and model
* mobile app version

**Comment by SedNomini** [comment]
> @SedNomini please fill out the entire issue template, including:
> 
> * phone make and model

IPhone SE- 

> * mobile app version
8.0.0

**Comment by jas14** [comment]
What is your iOS version?

Please try reinstalling the app and see if that helps, it's worked for some of our users in the past.

**Comment by SedNomini** [comment]
> 

It worked! Thank you for your help!
