### ISSUE TITLE
iOS App isn't functioning anymore since v 8.0.0

### ISSUE THREAD

**Issue by dahanbn** [lichess-org/lichobile#2264]
**Describe the bug**
App isn't able to retain login data and it isn't possible to login again or do anything useful in it. Funny enough, push is still working. I  will get push notifications about opponents moves but if I click on them I land in the app in that curious state.

**To Reproduce**
In general app is unresponsable. And I am not able to log back in.

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/4658596/206795676-6c208c5c-c3fd-42e4-b855-8512d9fd71a2.mp4

**Smartphone (please complete the following information):**
 - Device: iPhone 13 or iPad 10,9" 2022
 - OS: 16.1.2
 - Lichess App Version 8.0.0

**Additional context**
The problem started after upgrading the app to the latest version.

**Comment by bvbeek** [comment]
Same issue here on iPhone XS Max (16.1.2)
Same issue on iPad Pro (12.9 inch) (4e generatie) 16.1.1)

When reinstalling the app, it’s possible to sign in, but after clicking on Home you can’t click on any button anymore.
Not possible to start a game.

**Comment by jas14** [comment]
I think the upgrade to Capacitor 4 may have gone a little awry. Can you try uninstalling and reinstalling the app to see if that fixes the issue?

**Comment by jas14** [comment]
7.16.1 seems to be working on Android. If you're able to downgrade on iOS, please do so while we work on a fix.

**Comment by rainwolf** [comment]
> I think the upgrade to Capacitor 4 may have gone a little awry. I reproduced this on Android, but reinstall seems to have temporarily fixed it. Can you try uninstalling and reinstalling the app to see if that fixes the issue?

I did try reinstalling, it did not fix the issue. It let me sign in again, but the issue resurfaced on the next launch of the app

**Comment by veloce** [comment]
That's not capacitor 4.0. It's rather the timeline:
```
timeline.js:115 Uncaught TypeError: Cannot read properties of undefined (reading 'patron')
    at renderUblogLike (timeline.js:115:38)
    at renderTimelineEntry (timeline.js:71:20)
```

The json sent by the server is not what the app expect. I don't know why.

Server is sending:
```
[
  [
    "lukhas",
    {
      "name": "Lukhas",
      "patron": true,
      "id": "lukhas"
    }
  ],
  [
    "thibault",
    {
      "name": "thibault",
      "patron": true,
      "id": "thibault"
    }
  ]
]
```

And the app is expecting:
```
export interface TimelineData {
  readonly entries: ReadonlyArray<TimelineEntry>
  readonly users: {[username: string]: LightUser}
}
```

So I guess the 7.16.1 is working because the timeline is disabled. What is weird is the code that provoque the issue was added almost a year ago: https://github.com/lichess-org/lichobile/commit/6966956431e9cf6b2f10c3d2919cce83adb0233d

I have quickly looked at Lila code and I don't see a recent code change either...

**Comment by rainwolf** [comment]
When can this fix be expected to go into production?

**Comment by jas14** [comment]
It already is 🙂

**Comment by rainwolf** [comment]
Strange, in that case the fix didn't change anything for me. Even with reinstalling.

**Comment by rainwolf** [comment]
I take it back, it seems resolved now
