### ISSUE TITLE
Series of moves disappears (not recorded)

### ISSUE THREAD

**Issue by davinderc** [lichess-org/lichobile#2268]
I was playing a game and could make the choice between checkmate and collecting more material. I decided to collect more material and then checkmate. At that point the game seemed to freeze up for a second but didn't finish (no winner declared as it normally did). I reviewed the previous move (as in tapped going back) and suddenly all of the moves made after white's move 34 disappeared and my clock dropped to around 2:15, as if I hadn't played anything for a while. This is really strange because both of us played several moves that then suddenly disappeared. 

I'm running Android 13 on a Google Pixel 6 Pro. The app version is 7.16.1. The link to the game is below:
https://lichess.org/Er7nAi4O#67

**Comment by michael1241** [comment]
Due to server crash, apologies.
