### ISSUE TITLE
Reported a bug

### ISSUE THREAD

**Issue by yusufshimer** [lichess-org/lichobile#2276]
**Describe the bug**
A clear and concise description of what the bug is. A soldier eliminates other soldier while both were on the same line.

https://user-images.githubusercontent.com/119488985/209916593-724925a6-0aa3-4049-b344-15db061b781e.MOV

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by meenbeese** [comment]
google en passant
