### ISSUE TITLE
Training wrong for #9Xqrj

### ISSUE THREAD

**Issue by sl5net** [lichess-org/lichobile#2278]
**Describe the bug**
commanded best move not results in checkmate. 
but there is a move that ends in checkmate faster.

 https://lichess.org/training/9Xqrj

better move:

![Screenshot_20221231_021517](https://user-images.githubusercontent.com/5634759/210120853-afd4c9a4-200f-4c2b-bce6-3144401873f2.jpg)

**Comment by sl5net** [comment]
mistake

**Comment by jas14** [comment]
Be8 prevents checkmate :)
