### ISSUE TITLE
PGN import fails when pasted text contains non-breaking space Unicode characters 

### ISSUE THREAD

**Issue by jokrefta** [lichess-org/lichobile#2283]
**Describe the bug**
When importing a PGN, if you paste in text that contains the character U+00A0  (NO-BREAK SPACE), the import does not work.

**To Reproduce**
1. Go to "Import game" from the side menu
2. Type in `1.`
3. Copy a no-break space character from https://unicode-explorer.com/c/00A0
    - Then optionally use https://babelstone.co.uk/Unicode/whatisit.html to verify that your clipboard does in fact contain a non-breaking space character
4. Paste the character in the lichess app, then type `e4 e5`
    - The text box will now contain the text `1.[U+00A0]e4 e5` (with the text in brackets replaced by the actual character, of course)
5. Click "Import Game". The import fails with error "Something went wrong. Invalid PGN"

**Expected behavior**
No-break spaces are treated as normal spaces and do not break the import. 

Note that `1. e4 e5` (with normal spaces) is considered a valid PGN and imports successfully.

**Smartphone (please complete the following information):**
 - Device: Galaxy A52 5G
 - OS: Android 12
 - App Version 8.0.0

**Additional context**
I found this when trying to paste in a PGN exported from chess.com app (Options->Share->Copy from analysis view). Yes, apparently chess.com exports PGNs with these characters.

**Comment by lenguyenthanh** [comment]
This works now in prod

**Comment by jas14** [comment]
@lenguyenthanh the mobile clients submit UTF-8-encoded forms, so nbsp is encoded on the web and by mobile clients as `%C2%A0`:

```
pgn=1.%C2%A0e4%20e5
```

Can we add support for that?

**Comment by lenguyenthanh** [comment]
do we need to support that? I tested on both web and app client (ios), they both works.

**Comment by jas14** [comment]
Not sure when the Lila code was deployed but it works for me too now! 🎉
