### ISSUE TITLE
In mobile application no link for opening

### ISSUE THREAD

**Issue by icegood** [lichess-org/lichobile#2312]
**Describe the bug**

**To Reproduce**
1. Go to tournament with predefined opening.
2. In laptop itcis possible to click to link to see opening details, while on mobile it is not possible

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy tab s8 sm x700
 - OS: android 13

**Additional context**

**Comment by jas14** [comment]
Duplicate of #1242, #1385, #1191, and some others.
