### ISSUE TITLE
Underpromote with autoqueen enabled

### ISSUE THREAD

**Issue by Ddxcv98** [lichess-org/lichobile#2336]
Is it currently possible to underpromote when autoqueen is enabled? I know on the desktop version it is done by holding CTRL when moving the pawn.

If the answer is yes I'll just close the issue and people who have the same question can later view this post as an answer.

First of all, I would like to let you know from the start that I am not familiar with this repository, let alone the code itself. So am not sure if this has been discussed before and I apologize for potential mistakes.

In case the answer was no, my suggestion for mobile would be to hold down the 8th (or 1st) rank square for more than x milliseconds to enable a drop down menu similar to the desktop version.

Although, from my playing experience, it seems to me that the moves are sent to the server using an on press action, instead of on release. This is obviously the natural choice, in order to improve speed play, especially for bullet matches. This means that for my suggestion to work, there would need to be an exception for when a pawn is pushed to the last rank.

I know this exception can be controversial when it comes to bullet matches and time trouble situations, so an extra option could be added to enable this feature when autoqueen is also enabled.

If this feature is approved and no one currently has the time for it, I can take some time of my own to understand the code and try to implement it myself.

Thanks!

**Comment by jas14** [comment]
Hey @Ddxcv98, thanks for the detailed issue. Under promotion when auto promotion is enabled is not currently supported, nor do I believe there are plans to enable it.

In general, this repository is maintenance-only; that is, we're not accepting PRs for new features at this time, only bug fixes. The maintainer, veloce, is spearheading a total rewrite in Flutter. If you'd like to contribute, you can find out how by reading this guide: https://github.com/lichess-org/mobile/blob/main/CONTRIBUTING.md
