### ISSUE TITLE
Users can mess with clock 

### ISSUE THREAD

**Issue by iasper** [lichess-org/lichobile#2351]
users are available to move opponent clock,leave image, In a 5 minute match my opponent could move my clock to 14 minutes
![Screenshot_20230502-132516](https://user-images.githubusercontent.com/13477769/235766195-6ffcc178-b71b-42b8-9289-6ff051c14115.png)

**Comment by jas14** [comment]
Yes, players on lichess can grant their opponents more time. This is a feature, not a bug.
