### ISSUE TITLE
Wood 4 theme not loading

### ISSUE THREAD

**Issue by csaavedra** [lichess-org/lichobile#2354]
Wood 4, my default theme, doesn't load. Changing to another theme works, but when going back to Wood 4 , the previously loaded theme stays on. Upon startup, the board is just plain black as in the screenshot. This is Android.

![Screenshot_20230511-223214](https://github.com/lichess-org/lichobile/assets/2523171/99f6bafd-bc2e-4bc4-89aa-6e2b895b72f4)

**Comment by jas14** [comment]
Can repro on a Pixel, this doesn't seem specific to device manufacturers.

**Comment by csaavedra** [comment]
Is there any interest in fixing this or is the app dead and all efforts are going to the new one?

**Comment by jas14** [comment]
I've been looking into a fix, a bit strapped for time but I suspect it has to do with the size of the image. The wood4 theme image is by far the largest (about 800K, where the next largest is about 500K). The board images are base64-encoded and injected into the app via a data URI in the stylesheet.

**Comment by csaavedra** [comment]
Sorry to be lazy but can you point me out to the code where the image gets injected? I might be able to find what changed in Chromium but it would be helpful to know the format. Either Chromium got a bit more strict in the data it accepts or some size limit got in place.

**Comment by csaavedra** [comment]
OK, I am assuming this is done here https://github.com/lichess-org/lichobile/blob/master/src/theme.ts#L111 . From what I see this is done using CSS variables. This commit https://chromium.googlesource.com/chromium/src/+/e0129bea201b0009f2c7952e805123e369f6d96d%5E%21/ limits the size of CSS custom variables to 1 MB. If the base64-encoded image is larger than that, I suppose it won't load.

**Comment by jas14** [comment]
Fantastic find @csaavedra ! The base64 encoding for wood4 is about 1.1MB so that Is definitely the problem.

**Comment by csaavedra** [comment]
Could you test what happens if you don't use a CSS Variable but use the value directly? Since the stylesheet is generated it shouldn't matter. If that fixes the issue then we know we are onto something.

**Comment by jas14** [comment]
@csaavedra just tested and that does indeed solve the problem. I prefer to reduce the file size in the first place since there are a few lines that use the `--board-background` variable, so I've opened https://github.com/veloce/lichobile-themes/pull/2.

**Comment by csaavedra** [comment]
How does this fix get deployed, for instance, if you already have the board image downloaded?
