### ISSUE TITLE
Rating problem

### ISSUE THREAD

**Issue by amddima** [lichess-org/lichobile#2356]
When I play and win player who have rating much more than mine, I receive almost equal points like I win the same rating player. It was several times. 

I expected that rating points from wins definetly depend from players' rating difference

![Screenshot_20230516_015553](https://github.com/lichess-org/lichobile/assets/133716862/bbdc60d4-1955-4d82-ab27-d2f4f4b83f99)
![Screenshot_20230516_015518](https://github.com/lichess-org/lichobile/assets/133716862/5571ab30-1912-4baa-ad98-342972a61293)

**Comment by jas14** [comment]
Lichess uses the [Glicko 2 rating system](https://en.wikipedia.org/wiki/Glicko_rating_system). This is a complicated system with several inputs, including:

* your current ranking
* your opponent's current ranking
* the frequency and outcome of games you have played in the recent past, as well as your opponent's ranking in those games
* the frequency and outcome of games your _opponents_ had played recently at the time when they played against you

In any case, the rating system is entirely server-controlled, so it doesn't belong in the mobile repo. Hope this explanation helps.
