### ISSUE TITLE
Conditional Moves in Correspondence Games Don't Work Anymore

### ISSUE THREAD

**Issue by landry314** [lichess-org/lichobile#2370]
I have the most updated version of Lichess on Android and conditional moves in correspondence games have completely stopped working for me.

I deleted the data for the app and logged in again and still they don't work.

I don't understand. They look like they are working but when I hit the back arrow it just deletes them all.

Interestingly, I tried setting them on the web version and they show up in the app and it doesn't delete them. The app is just not saving them.

I am using LineageOS 20.0 (Android 13) and Lichess 8.0.0.

**Comment by snicholsdev** [comment]
I'm having the same issue on Android. Started on June 3rd, I believe, and it was working fine before. Also on the most recent version of the app.

**Comment by landry314** [comment]
yeah it's weird. also, notifications for correspondence games are not clickable most of the time anymore. ive had these two problems for weeks actually.

**Comment by jas14** [comment]
Can repro, we're not setting the `playerId` for some reason in the ForecastCtrl. Maybe some API changed. Looking into it now.

**Comment by jas14** [comment]
Found it: https://github.com/lichess-org/lila/commit/8287613defeaa8c2688be3a666c29ef2fd385a85#diff-f61a730f3cdd26249e2c8855594a09e2b957e8c0b3de53f58da12e63409abd30

**Comment by F1orian** [comment]
Same issue on IOS.
Premoves seem to work on the PWA though

**Comment by jarvelusa** [comment]
Same thing, the issue is only in the app on Android (in my case). It's incredibly annoying. I can create the premoves but after clicking the blue button to play nothing happens, and the only way forward is to delete the premoves and make a move.

**Comment by jas14** [comment]
[The fix](https://github.com/lichess-org/lila/commit/646cb1357ff203b2b2f84369301797db5fc4eedc) has been written, please be patient until it's deployed.

**Comment by snicholsdev** [comment]
Thank you for the hard work! Glad you guys were able to find a fix.

**Comment by jas14** [comment]
The fix is deployed
