### ISSUE TITLE
Big problem that most users suffer from

### ISSUE THREAD

**Issue by AyubxAbulQasem** [lichess-org/lichobile#2377]
We suffer from the problem of the vast difference in the level between the players in points, and the problem lies when you put a novice competitor like me with competitors who are much higher than me in experience and points, so I had to cancel the match, unfortunately, because I do not want to lose my points, so your application makes a mistake and bans me from playing for a certain period of time, and this problem we suffer  Including us, the users of this application, in the event that this problem is not resolved as soon as possible, we will resort to the courts and sue you, and we will launch a fierce media campaign on the application.

**Comment by jas14** [comment]
You are allowed to set a maximum rating difference when you start a match. You are not allowed to degrade the experience of other users by repeatedly cancelling games.
