### ISSUE TITLE
Pawn Glitches, Lost Many Games From It

### ISSUE THREAD

**Issue by YouSureAboutThat** [lichess-org/lichobile#2399]
### What happened?

When moving a pawn to c4 or f4, it will glitch back to c3 or f3 after the other player takes it. It shows that I moved to c4 or f4, it glitches back only when they take it. I even had a player give me 10 take backs and each time it shows I moved to c4, but they take it at c3. The game has become useless to me as this bug happens at any point in the game. This is on the app with android. 

### How can we reproduce the bug?

Play the game until your opponent can take a pawn at c3 or f3. You have a pawn at c2 or f2. You move a pawn to c4 or f4. Your opponent will take the pawn at c3 or f3 like you never moved to c4 or f4. 

### Expected behavior

To have the pawn to stay where I moved it...

### Device

Android s10

### Operating system

9.0

### App version

V8.0.0

**Comment by el-cucui** [comment]
It sure is En passant move
check this https://en.wikipedia.org/wiki/En_passant

**Comment by jas14** [comment]
As el-cucui mentioned, this is a legal move called "en passant." See https://github.com/lichess-org/lichobile/issues/1987#issuecomment-1013956773.
