### ISSUE TITLE
Error in pawn capture

### ISSUE THREAD

**Issue by prontok** [lichess-org/lichobile#2408]
### What happened?

White pawn cuts off a piece and does not capture it

### How can we reproduce the bug?

Game against a computer opponent (Stockfish 3 level)

### Expected behavior

The pawn must take the place of the piece it captures.

### Device

Xiaomi Mi 10 T Pro

### Operating system

Android 12

### App version

v8.0.0

### Additional context

https://github.com/lichess-org/lichobile/assets/90829636/23459210-23cf-4360-b2fc-a68a25d9db56

**Comment by jas14** [comment]
https://github.com/lichess-org/lichobile/issues/1987#issuecomment-1013956773

**Comment by DarkMortal** [comment]
That's called en-passant and no the capturing pawn doesn't place itself on the same square it captured the pawn from.

Kindly study the basic rules of chess.
