### ISSUE TITLE
Lichess supports electronic chessboard function

### ISSUE THREAD

**Issue by zhaohaiyan75** [lichess-org/lichobile#2411]
My friends and I developed an electronic chess board. Through the Bluetooth interface, we can obtain the current chess piece category of each chess square on the chess board. Therefore, by adding relevant functions to the current project, the same chess-playing process as on the phone/pad can be completed on a real chessboard (see the attached video demonstration). This chess-playing process is consistent with the real physical chess-playing experience. The supported forms of chess play can be online chess, offline chess with the computer, offline face-to-face chess, and chess starting from any position, including the opening and endgame. In addition, chess positions can also be obtained from electronic chess boards, allowing users to train on real chess boards.

I have completed the development of this feature. I am looking forward to your reply as to whether this feature can be adopted. 

Thanks.

https://github.com/lichess-org/lichobile/assets/49560468/4d19c5fa-ae25-4513-8e03-2f5a17991067

https://github.com/lichess-org/lichobile/assets/49560468/9636f633-9d95-4bf5-af78-c2c7bdcb0e8d

**Comment by fitztrev** [comment]
Thanks for sharing! This repo is for the old version of our mobile app, which won't be receiving feature updates. Please consider joining the Discord and sharing your project in the programming channels there where more will see.
