### ISSUE TITLE
Challenge friend fail

### ISSUE THREAD

**Issue by LangosLauko** [lichess-org/lichobile#2412]
### What happened?

When I want to challenge friend, app says "Resource not found"

### How can we reproduce the bug?

1. Click challenge friend
---
1. Click "friends online"
2. Click "challenge friend"

### Expected behavior

To challenge my.friend and start chess match

### Device

Samsung A52

### Operating system

Samsung

### App version

 v8.0.0

### Screenshots

![Screenshot_20231113_154017_lichess](https://github.com/lichess-org/lichobile/assets/73956186/1b8b29a2-2c56-48a9-9bdc-5b38ed191735)

**Comment by Lordydude** [comment]
Same problem here. 

Here,
https://github.com/lichess-org/lila/commit/28177708e71b54971b638d4e60d2afc21196617d?w=1

it says that there has been a recent code change and the changes are shown in code. I am unfit in SCALA 3, but as far as I can see, undoing that latest change could fix the problem - and then whoever did that change could test that change a little further (I dunno what the intention of that latest change was...). 

Who can perform such a software change?

**Comment by Lordydude** [comment]
btw, see also 
https://github.com/lichess-org/lila/issues/13980
