### ISSUE TITLE
Can't Challenge Any Players to a Game 

### ISSUE THREAD

**Issue by snicholsdev** [lichess-org/lichobile#2413]
### What happened?

Can't Challenge Any Players to a Game - Resource Not Found 

### How can we reproduce the bug?

1. When I visit a player's profile and attempt to challenge the player to a game.
2. See the resource not found message.

My wife (one of the players I've tried challenge) also can't challenge me. We're both on the latest version of the Android app.

I'm still able to do a rematch, but that doesn't notify the other player that I want a rematch unless they go to their games and view the game I sent the rematch from.

### Expected behavior

I expect a challenge to begin when challenging players

### Device

Google Pixel 5

### Operating system

Android 13

### App version

v8.0.0

**Comment by fitztrev** [comment]
Hi, this will be fixed in the next deploy. https://github.com/lichess-org/lila/issues/13980

**Comment by snicholsdev** [comment]
> Hi, this will be fixed in the next deploy. [lichess-org/lila#13980](https://github.com/lichess-org/lila/issues/13980)

Awesome. Thank you!
