### ISSUE TITLE
Unable to create an account on lichess with Tutanota email address

### ISSUE THREAD

**Issue by AYH8M** [lichess-org/lichobile#2417]
### What happened?

I encountered an issue while attempting to create an account on lichess using my Tutanota email address

### How can we reproduce the bug?

I encountered an issue while attempting to create an account on lichess using my Tutanota email address (@tutanota.com). When I entered my email during the registration process, I received an error message stating, "Cannot use disposable email addresses (DNS blocklist)." However, Tutanota is a legitimate and secure email service provider, and it should not be considered a disposable email address.

Steps to Reproduce:

1. Visit lichess website (https://lichess.org)
2. Click on "Sign Up" or "Create Account"
3. Enter Tutanota email address
4. Observe error message: "Cannot use disposable email addresses (DNS blocklist)"

Thank you for your attention to this matter.

### Expected behavior

I expect to be able to create an account on lichess using my Tutanota email address without encountering any error messages. Tutanota should be recognized as a valid email service provider and not blocked as a disposable email address.

### Device

Oppo Reno 5

### Operating system

Android 13

### App version

website 

### Additional context

- Tutanota is a reputable email service provider that offers secure and private email accounts.
- Blocking Tutanota email addresses might be an unintended consequence of an overreaching disposable email address filter.
- Tutanota email addresses are not disposable but rather provide robust encryption and privacy features.

Thank you for your attention to this matter.

**Comment by jas14** [comment]
Thanks for the feedback @AYH8M . This logic resides on the server, not the mobile app. These security decisions are usually based on observed patterns and experience, so I'm not sure how much luck you'll have, but you can try opening an issue on https://github.com/lichess-org/lila instead.

**Comment by AYH8M** [comment]
Ok thank you , have a great day
