### ISSUE TITLE
Incorrect piece advantage

### ISSUE THREAD

**Issue by Mercutio1243** [lichess-org/lichobile#2443]
### What happened?

In game review mode, next to player names the captured piece advantage is shown. For my recent game, not all captured pieces are displayed correctly, see screenshot.

### How can we reproduce the bug?

Open my game in mobile app:
https://lichess.org/StWLB6od/white#51

### Expected behavior

Piece advantage is displayed correctly 

### Device

Samsung Galaxy s21+

### Operating system

Android

### App version

V8.0.0

### Screenshots

![Screenshot_20240307_231156_lichess](https://github.com/lichess-org/lichobile/assets/152015018/c75f1a6f-49d1-4b55-85c2-e023abe20dfe)

**Comment by randompearl-stack** [comment]
Your screenshot was taken on [https://lichess.org/StWLB6od/white#49](url), not https://lichess.org/StWLB6od/white#51, the end of the game. The piece difference is displayed correctly on move 25.
