### ISSUE TITLE
Atomic chess, stockfish moves while in check

### ISSUE THREAD

**Issue by matgaj** [lichess-org/lichobile#2453]
### What happened?

Stockfish made a move while under check, exploding my king, while its king was still under check from my knight 

### How can we reproduce the bug?

Here’s the PGN:
[Event "Casual Atomic game"]
[Site "https://lichess.org/F797vIER"]
[Date "2024.03.30"]
[White "bbazil"]
[Black "lichess AI level 3"]
[Result "0-1"]
[UTCDate "2024.03.30"]
[UTCTime "19:31:03"]
[WhiteElo "1500"]
[BlackElo "?"]
[Variant "Atomic"]
[TimeControl "-"]
[ECO "?"]
[Opening "?"]
[Termination "Normal"]
[Annotator "lichess.org"]

1. Nc3 c6 2. e4 Nf6 3. g4 d5 4. Qe2 Qb6 5. d4 Qa6 6. Nb5 h5 7. Nc7+ Qxe2# { Game ends by variant rule. } 0-1

### Expected behavior

Opponent is forced to escape check before making any other move 

### Device

iPhone 12

### Operating system

17.4.1

### App version

v8.0.0

### Screenshots

![IMG_5443](https://github.com/lichess-org/lichobile/assets/10777373/17b43c52-ea22-41e3-9a64-91f482c68101)
![IMG_5444](https://github.com/lichess-org/lichobile/assets/10777373/674c1a2e-d1b2-4da8-a46d-a598611be85e)
![IMG_5445](https://github.com/lichess-org/lichobile/assets/10777373/41dd82bd-7855-416a-9e4f-93daad29fd53)

**Comment by randompearl-stack** [comment]
This is not a bug, it is how the variant was intended to be played. [https://lichess.org/variant/atomic]( https://lichess.org/variant/atomic) 

> Traditional checkmate applies to atomic as well, but **any move that results in blowing up the opposite king will result in an immediate victory, overriding all checks and checkmates.**
