### ISSUE TITLE
IMPOSSIBLE MOVE

### ISSUE THREAD

**Issue by EdvardsZ** [lichess-org/lichobile#2454]
### What happened?

I made a impossible move.

### How can we reproduce the bug?

1. Go to this url: https://lichess.org/FLYa3aYs/white#39
2. See move 20.
3. IMPOSSIBLE MOVE

### Expected behavior

I should not be able to do that.

### Device

Xiaomi POCO X3 NFC

### Operating system

Android

### App version

v8.0.0

### Screenshots
![image](https://github.com/lichess-org/lichobile/assets/52094363/ce48006d-4840-426f-a72b-baaf6f432c74)

Hello, I played 10 minute game and I think I made a impossible move. I am begginer in chess so I could be wrong.

https://lichess.org/FLYa3aYs/white#39 see move 20.

**Comment by jas14** [comment]
https://lichess.org/learn#/15
