### ISSUE TITLE
Board squares are drawn as rectangles on low-resolution displays

### ISSUE THREAD

**Issue by mason0190** [lichess-org/lichobile#2471]
### What happened?

The board on a low-resolution (mine is 480x640) screen draws as a rectangle, ruining piece placement

### How can we reproduce the bug?

1. Open the app on a device with a low-resolution display
2. Open a puzzle, game, study or otherwise draw a board
3. Look at the weird looking squares

### Expected behavior

Board is a perfect square that lines up with the pieces on top of it

### Device

Cat S22 FLIP

### Operating system

Android Go v11

### App version

v0.8.17

### Screenshots

![Screenshot_20240606-142207](https://github.com/lichess-org/lichobile/assets/4924152/21fb6f48-b030-4bdb-937b-dd5d44298c37)

### Additional context

The old lichess app looked even worse on this screen, but it was at least square

**Comment by jas14** [comment]
@mason0190, thank you for the report. This repository is for the old mobile app; please reopen this issue on https://github.com/lichess-org/mobile. Thanks again!
