### ISSUE TITLE
Coordinate system in the new android app

### ISSUE THREAD

**Issue by mshahedi83** [lichess-org/lichobile#2472]
### What happened?

in white side "a, .., h" begins from right

### How can we reproduce the bug?

1. Open the new app
2. go to the watch
3. select a game to watch
4. Pay attention to the coordinates of the squares
5. Compare them with coordinates of the squares in  website

### Expected behavior

in white side "a, .., h" begins from left

### Device

Samsung Galaxy A34

### Operating system

Android 14

### App version

v0.8.17

### Screenshots

![Screenshot_۲۰۲۴۰۶۰۷_۱۰۵۰۰۸_Chrome](https://github.com/lichess-org/lichobile/assets/88142574/c2817315-e20c-42f9-9321-ce1849832dbb)
![Screenshot_۲۰۲۴۰۶۰۷_۱۰۵۰۱۲](https://github.com/lichess-org/lichobile/assets/88142574/81f8b696-ff6b-41c0-9db1-824354662d4e)

### Additional context

Hello, by reading [this post](https://lichess.org/@/Lichess/blog/the-new-mobile-app/KXlgb3X2), I realized that a new app has been released; I was really surprised by this news.
but when i went to watch to see some games and change the board style, I noticed that there seems to be something wrong in the coordinate system!

It seems that the direction of "a, b, c, ..., h" is reversed, but apparently, even though the numbers (1, 2, 3, ..., 8) are written in the right direction, but it seems that they aren't in the right place (relative to the site).

Good luck!
Thanks.

**Comment by mshahedi83** [comment]
i think the problem happens because my device language is persian that is RTL language, so the next and previous move buttons, the direction of the moves written on the top, username is after clock and etc.

**Comment by jas14** [comment]
@mshahedi83 , thanks for the report. This repository is for the old repo – please move the issue to https://github.com/lichess-org/mobile. Thanks again!
