### ISSUE TITLE
Mark as "won" if the opponent's account has been banned

### ISSUE THREAD

**Issue by Feriman22** [lichess-org/lichobile#2475]
**Is your feature request related to a problem? Please describe.**
Currently we have to wait till the time passes before won, however the opponent's account has been banned.

**Describe the solution you'd like**
Mark as winner, if the opponent cannot move anymore.

![Screenshot_2024-06-07-21-19-50-394_org lichess mobileapp](https://github.com/lichess-org/lichobile/assets/22872515/2e304148-1f69-4b6f-9383-c5551a6830c4)

**Comment by jas14** [comment]
@Feriman22 thanks for the suggestion. Game termination is controlled on the server, so please check out the [instructions for suggesting a feature on lila](https://github.com/lichess-org/lila/blob/master/CONTRIBUTING.md#i-want-to-suggest-a-feature-for-lichess).
