### ISSUE TITLE
Move notation setting not respected in new app

### ISSUE THREAD

**Issue by LukeyPmoney** [lichess-org/lichobile#2477]
### What happened?

In the new app, the list of moves is always in letter notation when playing a game, but the analysis board always shows moves in figurine notation. Also, this setting can only be updated on the website, not in the app.

### How can we reproduce the bug?

On the website, click/tap profile icon -> preferences -> display. Change the Move Notation setting to the opposite of what it was and save.
Next, start a game in the lichess app: game moves notation will be in letter form regardless of move notation setting. Switch to analysis board: game moves and moves within analysis lines are always in figurine notation, regardless of move notation setting.

### Expected behavior

Move Notation setting should be respected in the app. This setting should also be available to change in the new app.

### Device

Samsung Galaxy S7

### Operating system

Android 8.0.0

### App version

0.8.17

**Comment by jas14** [comment]
Hi there, sounds like this issue belongs in the repository for the new app: https://github.com/lichess-org/mobile .
