### ISSUE TITLE
Probleme 

### ISSUE THREAD

**Issue by XKHALIL7** [lichess-org/lichobile#2478]
### What happened?

Game ended without quiting the game

### How can we reproduce the bug?

BEN_KHALIL  account
Third game 
Last mouve 
Bichop chek ( normal chek ) game ended while  i didnt exit

### Expected behavior

Review the game and give me my elos back

### Device

Samsung A02

### Operating system

Android 11

### App version

Last one 

### Additional context

https://lichess.org/ZBWsaZvj/black#57

**Comment by ACAne1949** [comment]
There is no interface for promotion pieces selecting after pawns reach the side line.

**Comment by jas14** [comment]
Duplicate of #1793. @ACAne1949 I hope you find something in that issue that will help!
