### ISSUE TITLE
Lag in game

### ISSUE THREAD

**Issue by Pjagui** [lichess-org/lichobile#2480]
### What happened?

The game response is slow. Not to good to play Bullet. Even without the pieces animations 

### How can we reproduce the bug?

1. Create a game. 

### Expected behavior

I want pieces to move quicker. In Bullet variant

### Device

Galaxy s22 ultra

### Operating system

Android 14

### App version

V0.8.17

**Comment by jas14** [comment]
Hello, this is the repository for the old app. Please reopen the issue here: https://github.com/lichess-org/mobile/issues

Thanks!
