### ISSUE TITLE
Can't make any move in Antichess

### ISSUE THREAD

**Issue by ZendakGT** [lichess-org/lichobile#2482]
### What happened?

I'm playing Antichess, is my turn yo move but the platform doesn't allow me to. I can't make any move, although there are plenty of options.

### How can we reproduce the bug?

I dont know how to share here the ongoing game, but Is the one in the attached image.

![Screenshot_20240615_153706](https://github.com/lichess-org/lichobile/assets/172937552/698f08d4-1189-4bee-914c-efd52e00cd79)

### Expected behavior

That I can continue the game :)

### Device

Honor 90

### Operating system

Android

### App version

V8.0.0

### Screenshots

![Screenshot_20240615_153706](https://github.com/lichess-org/lichobile/assets/172937552/4e8ed9d8-54ba-4b93-a5d4-b2782bc36fc9)

**Comment by Aakash3708** [comment]
> ### What happened?
> 
> I'm playing Antichess, is my turn yo move but the platform doesn't allow me to. I can't make any move, although there are plenty of options.
> 
> ### How can we reproduce the bug?
> 
> I dont know how to share here the ongoing game, but Is the one in the attached image.
> 
> ![Screenshot_20240615_153706](https://github.com/lichess-org/lichobile/assets/172937552/698f08d4-1189-4bee-914c-efd52e00cd79)
> 
> 
> ### Expected behavior
> 
> That I can continue the game :)
> 
> ### Device
> 
> Honor 90
> 
> ### Operating system
> 
> Android
> 
> ### App version
> 
> V8.0.0
> 
> ### Screenshots
> 
> ![Screenshot_20240615_153706](https://github.com/lichess-org/lichobile/assets/172937552/4e8ed9d8-54ba-4b93-a5d4-b2782bc36fc9)
> 
> 
> ### Additional context
> 
> _No response_

I think you may want to check where does that white bishop of yours is aiming at

**Comment by jas14** [comment]
@ZendakGT , as @Aakash3708 pointed out, you are required to play Bxa6. This appears to be the only legal move per the rules of antichess.
