### ISSUE TITLE
When exporting a PGN for an Analysis, none of the tags save. 

### ISSUE THREAD

**Issue by TheForkPower** [lichess-org/lichobile#2483]
### What happened?

My game tags in the exported PGN are not saved.

### How can we reproduce the bug?

1. Make a new analysis on the Lichess beta app.
2. Play some moves
3. Press the hamburger then Export PGN
4. Fill in the tags with filler names and places etc,
5. Then press OK
6. Copy the PGN into a plain text editor like Google Docs
7. You will see the tags you inputted on the Lichess app just a second ago don't appear on the PGN

### Expected behavior

I expected to see the tags.

### Device

Samsung S20

### Operating system

Android

### App version

PUBLIC BETA

**Comment by jas14** [comment]
@TheForkPower , @randompearl-stack is correct - please reopen this issue in the linked repository. Thanks!
