### ISSUE TITLE
Puzzle Storm - redoing puzzles affects ranking

### ISSUE THREAD

**Issue by catherine-toolan** [lichess-org/lichobile#2484]
### What happened?

Redoing puzzles in the puzzle storm mode after runs increases and decreases overall puzzle ranking

### How can we reproduce the bug?

Go to puzzle storm, do a run, redo one of the puzzles (easier to see when failing a puzzle) and puzzle rating goes down

### Expected behavior

No impact on overall puzzle ranking

### Device

Samsung Galaxy A22

### Operating system

Android 14.0

### App version

v0.8.17

**Comment by jas14** [comment]
Hello, this is the repository for the old app. Please reopen the issue here: https://github.com/lichess-org/mobile/issues

Thanks!
