### ISSUE TITLE
[Beta App] Stuck state when connection lost

### ISSUE THREAD

**Issue by cavollopollo** [lichess-org/lichobile#2485]
### What happened?

After losing connection and coming back, the app doesn’t update the game state and there is no way to leave the game, forcing the user to restart the application

### How can we reproduce the bug?

In the new Beta App, I was playing a match, I lost connection for about 2 minutes.

After the connection was back, and losing the game for disconnection, the application did not update the game and thought its still going on. Therefore there was no way to exit the game screen, leaving the user stuck in the app.

A hook on connection re-established to update the game state is probably required, or more simply just a retry policy in the match state when the connection is lost.

A separate, larger proposal is to include more navigation options in the game screen, to go back to the main page.

### Expected behavior

The app should realize the game was over / lost

### Device

iPhone 14 Pro

### Operating system

Latest

### App version

Beta

**Comment by jas14** [comment]
Hello, this is the repository for the old app. Please reopen the issue here: https://github.com/lichess-org/mobile/issues

Thanks!
