### ISSUE TITLE
Erroneous checkmate

### ISSUE THREAD

**Issue by QloudStrife** [lichess-org/lichobile#2490]
### What happened?

I was place in check but the game called it as checkmate.

### How can we reproduce the bug?

See screenshot

### Expected behavior

Check, then capture bishop.

### Device

S24

### Operating system

Android 14

### App version

8

### Screenshots

![Screenshot_20240714_063419_lichess](https://github.com/user-attachments/assets/ce917eef-0db3-4c40-860d-68b2783551ac)

**Comment by jas14** [comment]
Game in question is https://lichess.org/FTlapHig/white

You'll notice that this was not checkmate; the Lichess servers believe you left the game. Perhaps you lost Internet connection?
