### ISSUE TITLE
Profile in new App android

### ISSUE THREAD

**Issue by ojarke** [lichess-org/lichobile#2494]
### What happened?

It not possible to record the profile details. Aparently, it works fine, but after saving data, the system doesn't record the data and appears in blank.

### How can we reproduce the bug?

Going to profile in App lichess v2.

### Expected behavior

See "what happened"

### Device

samsung S24 plus

### Operating system

Android

### App version

V

### Screenshots

 0.9.3

**Comment by jas14** [comment]
Please reopen this issue on the repository for the new app, https://github.com/lichess-org/mobile
