### ISSUE TITLE
Partidas Personalizadas Bug Report (Ptbr)

### ISSUE THREAD

**Issue by CloneVermelhoBR** [lichess-org/lichobile#2498]
### What happened?

Ao selecionar a cor branca em uma partida personalizada a mesma não e escolhida

### How can we reproduce the bug?

1 partida personalizada 
2 selecionar as cores brancas
3 selecionar valendo rating
4 iniciar partida

### Expected behavior

...

### Device

...

### Operating system

...

### App version

...

**Comment by jas14** [comment]
Duplicate of #2501
