### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ilidv3331** [lichess-org/lichobile#2500]
### What happened?

My email address iliadv333@gmail.com, but I can't register. Lichess writes  that I have an error whis the email address.  Please help me.

### How can we reproduce the bug?

My email address iliadv333@gmail.com, but I can't register. Lichess writes  that I have an error whis the email address.  Please help me.

### Expected behavior

My email address iliadv333@gmail.com, but I can't register. Lichess writes  that I have an error whis the email address.  Please help me.

### Device

Samsung a25

### Operating system

Android

### App version

Last

### Screenshots

My email address iliadv333@gmail.com, but I can't register. Lichess writes  that I have an error whis the email address.  Please help me.

### Additional context

My email address iliadv333@gmail.com, but I can't register. Lichess writes  that I have an error whis the email address.  Please help me.

**Comment by jas14** [comment]
This is the codebase for the old mobile app - the issue you're describing is controlled by the server.
 Please read https://github.com/lichess-org/lila/blob/master/CONTRIBUTING.md#i-want-to-report-a-bug-or-a-problem-about-lichess
