### ISSUE TITLE
Error al crear una partida

### ISSUE THREAD

**Issue by Seba19800** [lichess-org/lichobile#2501]
### What happened?

Al ir a crear una partida personalizada y solicitar de jugar con el color blanco , me dan para jugar con negras. Esto esta sucediendo todo el tiempo, x lo que cancele las partidas y fui penalizadoi

### How can we reproduce the bug?

Go to crear una partida
Perosnalizado
Color :blancas

### Expected behavior

Al seleccionar de jugar con blancas deberia darme blancas para jugar

### Device

Motorola 

### Operating system

Android

### App version

Version

**Comment by jas14** [comment]
@Seba19800 por favor, rellena el formulario completamente. Por ejemplo, no se puede saber cual versión del app usas, lo que es importante para resolver este problema.

**Comment by jas14** [comment]
Could not reproduce on this app. Reproduced on the new Flutter rewrite. See https://github.com/lichess-org/mobile/issues/1020.
