### ISSUE TITLE
System dropped my rating from 1698 to 1651 in rapid

### ISSUE THREAD

**Issue by Almershed122** [lichess-org/lichobile#2505]
### What happened?

The system dropped my rating from 1698 to 1651 in rapid

### How can we reproduce the bug?

Check my account chraimbaaaa

### Expected behavior

correcting the rate

### Device

iPhone Xs Max

### Operating system

iOS 17.5.1

### App version

v7.6.5

### Screenshots

![IMG_3362](https://github.com/user-attachments/assets/f2a047a1-8edd-4d58-a487-2c06343ed1fd)

**Comment by jas14** [comment]
https://lichess.org/forum/lichess-feedback/regarding-recent-rating-posts#1
