### ISSUE TITLE
Error de puntaje 

### ISSUE THREAD

**Issue by Victor2049v** [lichess-org/lichobile#2506]
### What happened?

Mi puntaje estaba en 1680, y cuando perdí la partida me apareció "-5, es decír, mi puntaje tuvo que quedar en 1675 y no en 1671, es decir, me quitaron 4 puntos sin motivo alguno"

### How can we reproduce the bug?

![Screenshot_2024-09-24-11-12-18-764_org lichess mobileapp](https://github.com/user-attachments/assets/e17ab5e3-6a1b-4a99-827e-8d2a903b775c)

### Expected behavior

Esperaba que me pusieran el puntaje correctamente, es decir, de 1680 a 1675. Además contando los puntos de la última partida que gané

### Device

Poco x3 pro

### Operating system

Android 11

### App version

Última versión disponible 

### Screenshots

![Screenshot_2024-09-24-11-24-08-318_com android chrome](https://github.com/user-attachments/assets/6a0881dd-9c26-4722-a0f5-03e989ef23ab)

**Comment by jas14** [comment]
https://lichess.org/forum/lichess-feedback/regarding-recent-rating-posts#1
