### ISSUE TITLE
my bullet rating gone from 2345 to 2264 for no reason my id T-MUTHUKUMAR

### ISSUE THREAD

**Issue by muthukumartc** [lichess-org/lichobile#2507]
### What happened?

my bullet rating gone from 2345 to 2264 for no reason. pls check in my games i started to play on the app and won many games it showed right increment in my bullet rating then suddenly dropped from 2345 to 2264 dont know why

### How can we reproduce the bug?

1. play games on lichess app my 
2. rating gained 
3. they reduce rating 
4. look at my games in my bullet its showed correct raing in games but in profile it showed 2267

### Expected behavior

i won games rating increased properly ,but  all the sudden its dropped .why?

### Device

oneplus 11

### Operating system

oxygen OS ANDROID 14

### App version

0.11.0

### Screenshots

![Screenshot 2024-09-24 215425](https://github.com/user-attachments/assets/236617e8-65fb-43eb-a837-d55c57f995ba)
![Screenshot 2024-09-24 215442](https://github.com/user-attachments/assets/11ec092e-253b-4524-abcf-339e4ae1e06e)

### Additional context

 RETURN MY HARD EARING RATING POINTS .. DISAPPOINTED WITH THIS INCIDENT .MY ID  T-MUTHUKUMAR

**Comment by jas14** [comment]
https://lichess.org/forum/lichess-feedback/regarding-recent-rating-posts#1
