### ISSUE TITLE
Study issue 

### ISSUE THREAD

**Issue by Ankanahadoww** [lichess-org/lichobile#2512]
### What happened?

When selecting any study, it just opens up an empty board and a loading animation, but the loading never resolves.

### How can we reproduce the bug?

1. Go to study section 
2. Open any study 
3. You will find the bug

### Expected behavior

Study section is opening as soon as possible 

### Device

Iqooz7

### Operating system

Android 14

### App version

V8.0.0

**Comment by jas14** [comment]
Duplicate of #2509
