### ISSUE TITLE
"Always promote to queen" still asks which piece to promote to

### ISSUE THREAD

**Issue by patc3** [lichess-org/lichobile#2513]
### What happened?

Using mobile app beta, in preferences I have auto promote to queen set to "always", yet I was playing a bullet game and had to manually pick the piece to promote to

### How can we reproduce the bug?

Promote a pawn

### Expected behavior

Promote to queen if automatically promote to queen is set to always

### Device

Samsung A71

### Operating system

Android

### App version

v0.11.0

**Comment by jas14** [comment]
Thanks for the report but this is the repository for the old mobile app, please reopen on https://github.com/lichess-org/mobile.
