### ISSUE TITLE
Disable move confirm when low on time

### ISSUE THREAD

**Issue by ZenoG2** [lichess-org/lichobile#2515]
**Issue description**
I hate that when the time is low you need to confirm each move. That's not what you're looking for when you have 20 seconds on the clock. Disable move confirmation when the time is low or when playing bullet games.

**Comment by jas14** [comment]
@ZenoG2 there's already a setting to enable move confirmation for correspondence games:

![Screenshot_20241003-080046](https://github.com/user-attachments/assets/239886f5-5f07-43be-9d22-8e45120be0a4)

Hope this helps!

**Comment by ZenoG2** [comment]
I don't play correspondence. This option would be useful to prevent mouse slips while still maintaining a high degree of speed.

**Comment by jas14** [comment]
@ZenoG2 is this a request for the website? If so, see https://github.com/lichess-org/lila

**Comment by ZenoG2** [comment]
Oh, whoops
Silly me 😅
