### ISSUE TITLE
Жалоба

### ISSUE THREAD

**Issue by Olk134** [lichess-org/lichobile#2517]
### What happened?

Hello!   My account is OLK134. I played today, didn’t leave any matches, finished everything, and didn’t make my opponent wait. However, I received this message (I’m attaching a screenshot) claiming that I allegedly violated one of the rules in the screenshot, which I did not do. This is not the first time this has happened.    I don’t fully understand how the system on the website works, but I suspect that someone might be getting upset about losing and consequently reports me. What can I do to minimize such situations?

### How can we reproduce the bug?

1. Играть
2. Ждать когда прилетит ошибка

### Expected behavior

Я ожидала не увидеть этого сообщения

### Device

Sumsung a53

### Operating system

Android 14

### App version

V 8.0.0

### Screenshots

![Screenshot_20241007_154554_lichess](https://github.com/user-attachments/assets/7e83b994-8299-442f-8244-eb9d523e7928)

**Comment by jas14** [comment]
This is the repository for the old mobile app – we don't issue bans, that's done server-side. See https://lichess.org/page/appeal.

**Comment by Olk134** [comment]
Let's say I've read the link. How should this help me? Are you saying that I should appeal?

**Comment by jas14** [comment]
@Olk134 yes:

> You should use [lichess.org/appeal](https://lichess.org/appeal) if your account has been restricted, banned, closed, or otherwise marked by Lichess moderators and you wish to appeal the decision.
