### ISSUE TITLE
F-droid version does not support notifications

### ISSUE THREAD

**Issue by kuba-orlik** [lichess-org/lichobile#2523]
### What happened?

When using the f-droid versions, there's no way to enable notifications when the opponent makes their move

### How can we reproduce the bug?

1. Install Lichess from F-droid
2. Open the app and go to settings
3. No notification options
4. Uninstall lichess
5. Install Lichess from the latest GH release
6. Open the app
7. See there are options to configure notifications

### Expected behavior

Notifications can be anbled on f-droid version

### Device

Pixel 7a

### Operating system

Android 14

### App version

v8.0.0

**Comment by jas14** [comment]
This project depends on non-free Google services for push notification support. Those are specifically disabled for the F-Droid build. See #1121 .
