### ISSUE TITLE
Timeout vs opponent with a bishop & king only

### ISSUE THREAD

**Issue by franraknic** [lichess-org/lichobile#2531]
### What happened?

I (black) timed out with two pawns and a king, the opponent (white) has a bishop and a king. Is this not supposed to be a draw?

### How can we reproduce the bug?

Link to the game:
https://lichess.org/4I70Be3A/black#119

### Expected behavior

Game is supposed to draw since white can't checkmate.

### Device

Xiaomi 14 Lite

### Operating system

Android 14

### App version

v8.0.0

**Comment by BrahiMac** [comment]
Technically this is not a draw.. as you may blender the bishop and black will win easly.

**Comment by jas14** [comment]
BrahiMac is correct. Draws are not forced unless there is insufficient material to checkmate. One or both of the pawns in the game you linked could theoretically be promoted.

**Comment by franraknic** [comment]
Guys thanks for the replies. But black lost here (timed out) while **white** has only the bishop and king - can't mate.
So white won, with insufficient material to draw.

![image](https://github.com/user-attachments/assets/fedd7f06-3ab6-4691-aca4-f72fcbda49a8)

**Comment by jas14** [comment]
Ah, I see. However, it is actually possible to mate with a king and bishop as long as the opponent still has a piece on the board, e.g. https://lichess.org/editor/8/8/8/8/1B6/8/p7/k1K5_w_-_-_0_1?color=white . 

Anyway, game outcome is determined server-side, so the mobile apps can't address it. See https://github.com/lichess-org/lila/issues/9249 for further discussion.

**Comment by franraknic** [comment]
Thank you for providing the example of a checkmate and for pointing me to the discussion. The game I linked could indeed be among the "unfair" ones. 

This is clearly a server-side issue, that is still open for discussion. Thanks again, very helpful!
