### ISSUE TITLE
Correspondence confirm move behavior 

### ISSUE THREAD

**Issue by deathanchor** [lichess-org/lichobile#2536]
**Problem:**
In a correspondence game with confirm move option. If you make a move, hit back arrow, confirm move dialog stays. If you hit X to decline, it backs out the opponents move. If you hit confirm, it will appear you didn't make a move and now opponent's turn. Exiting the game view, and viewing game again shows correct state.

**Describe the solution you'd like**
Pressing back move button should remove move confirmation question.

**Additional context**
I will attach video of screen recording of this happening.

Replicated on Android version of the beta app v0.12.6.

**Comment by deathanchor** [comment]
https://github.com/user-attachments/assets/da26574c-b80d-45bc-8d7c-47cd1e0cdf69

Video

**Comment by vovagorodok** [comment]
V2 version of app has new repository: https://github.com/lichess-org/mobile

**Comment by deathanchor** [comment]
Please close this issue as I've moved it to the correct repository:
https://github.com/lichess-org/mobile/issues/1329
