### ISSUE TITLE
Tactics training repeats already solved positions

### ISSUE THREAD

**Issue by gcp** [lichess-org/lichobile#876]
- bug report

Open Android app, go to training. Observe that the puzzle is a familiar one: it has been solved on the lichess.org website the week before. Same for all following puzzles.

**Expected behavior:**

If an internet connection is present, puzzles that were already solved should not be repeated.

(If no connection is present, it would be nice if the batch of 50 that is downloaded was seeded in a different way from the website, to make it very unlikely that one gets dupes. Might also fix this bug.)

lichess seems to know the puzzle has already been solved, as my rating does not change.

**Environment information**

- Android 8.1
- Pixel 2 XL
- App version 6.0.4

**Comment by veloce** [comment]
I acknowledge the problem, but this is also server side to me. That'd be nice to open as well a ticket on ornical/lila as well, pointing this one as reference. Server issue will be a better place to discuss the solution to the problem.

**Comment by gcp** [comment]
Can you file that? I'm not clear what the underlying issue is? No API to probe whether positions are already solved? Or wanting the ability to "seed" the selection of positions that one gets?

**Comment by veloce** [comment]
Yes I'm going to report the issue.

**Comment by KommX** [comment]
@veloce Is there anything we could do to improve the situation with the puzzles?

**Comment by supertorpe** [comment]
I have implemented a workaround that consists of a button to resynchronize the puzzles. For it:
1) I added a method "database.clean": return asyncStorage.removeItem (`offlinePuzzles. $ {UserId}`)
2) new method "TrainingCtrl.resync" that invokes database.clean and syncAndLoadNewPuzzle
3) new "fa-refresh" button in TrainingView
In summary: when the resynchronization button is pressed, the local puzzle cache is emptied and a new one is loaded from the server.

**Comment by jakub-g** [comment]
As a kind of workaround for this issue, it would be handy to be able to
- skip a puzzle, or
- have a "random puzzle" button, or
- open a puzzle by id.

In the browser I can just change the URL to some random ID, but in mobile app there's no such possibility.

**Comment by veloce** [comment]
No more relevant with new puzzle api it seems.
