### ISSUE TITLE
Inbox message content should respect Android notification privacy

### ISSUE THREAD

**Issue by gcp** [lichess-org/lichobile#880]
Right now, if you get a message from someone through lichess's built in messaging system, the contents is fully displayed in the lock screen notification (which is always-on in many new phones). Android 5.0 and later add a privacy mode that (if enabled) hides the sensitive contents of notifications if the user enables the option. Logically, notifications about moves in games or correspondence would not be private, but inbox messages should be.

I've investigated properly supporting this in the lichess mobile app, but it doesn't look good. The notification handling is all handled by oneSignal, and their SDK for Cordova seems to be very limited. Notably, there's issues like these: https://github.com/OneSignal/OneSignal-Android-SDK/issues/174 but these are for pure Android. This concept doesn't seem to be exposed through their Cordova API.

So I suspect we'll need to file an issue upstream first to get this fixed in the Cordova SDK (if they want to do it...) before it would be feasible for the lichess app. Can anyone confirm/deny this?

By the way, when reading the oneSignal docs, I noticed: "Best of all, OneSignal is a free service that supports unlimited devices and notifications. **OneSignal makes money by selling data to advertisers and research companies.** We also offer paid service options for clients that require increased data privacy."

They collect quite some things:
https://documentation.onesignal.com/docs/data-collected-by-the-onesignal-sdk

And because of this there's various GDPR-getting-approval related APIs on their SDK. lichess mobile doesn't use any of them and seems to assume consent. If lichess doesn't have a paid contract with OneSignal this is a bit awkward.

**Comment by veloce** [comment]
Hi @gcp 

About issue 1, unfortunately you're right, if this privacy mode is not supported by onesignal sdk, we can't do nothing on lichess app.

As for the second issue you've raised, this is indeed a big concern. Lichess currently doesn't have a paid contract with OneSignal. Lichess team is discussing this matter to find a solution, and will try to contact OneSignal. Also next app release should include logic to get user consent before activating push notification service.

**Comment by GPery** [comment]
Relevant mention that using a different SDK for notifications will also rid lichess of the small piece of proprietary code (as OneSignal uses some non-free PlayStore features) and allow the app to be uploaded to F-Droid.

**Comment by veloce** [comment]
Fixed as we're using firebase now.
