### ISSUE TITLE
Notifications not received in real time

### ISSUE THREAD

**Issue by KnightAzul** [lichess-org/lichobile#904]
I'm submitting a: bug report

# Bug report

**Current behavior:**

Notifications for correspondence games (new challenge, new move made, etc.) are not received in real time in Android Nougat 7.1.1, when the screen has been off for more than a few minutes. When the screen is turned on the notifications are immediately presented. This seemed like it was Android Doze functionality kicking in. However, setting the Lichess app to not be "battery optimised" and therefore not affected by Android Doze, makes no difference. The notifications still are not received in real time when the screen has been off for more than a few minutes.

This bug does not exist when playing Lichess on Android Lollipop.

**Expected behavior:**

When setting the Lichess app to not be "battery optimised" and therefore not affected by Android Doze, the notifications should be received in real time in Android Nougat 7.1.1 even when the screen has been off for more than a few minutes. 

**Steps to reproduce:**

Play a correspondence game.

**Environment information**

Phone BQ Aquaris X
Android 7.1.1
Lichess 6.0.4

**Other information:**

None.

**Comment by veloce** [comment]
No more relevant with firebase.
