### ISSUE TITLE
Three-check check count doesn't adjust when rewinding game

### ISSUE THREAD

**Issue by greg-finley** [lichess-org/lichobile#919]
**I'm submitting a ...** 
- bug report

**Current behavior:**

When you rewind through a game using the arrows, the material difference at each move is properly reflected, but the number of checks is not.

**Expected behavior:**

Properly reflect the number of checks at the given move when rewinding. For instance, on the first move, both players have 0 checks so far.

**Steps to reproduce:**

Find a three-check game and step through it back to earlier moves / the first move.

**Environment information**

- phone hardware: iPhone XS
- phone operating system version: iOS 12.1
- version of lichess mobile: v6.0.0

**Other information:**

End of the game:

![image](https://user-images.githubusercontent.com/28961086/49128665-41984000-f281-11e8-91d7-d0d39a0b249c.png)

Beginning of the game (where the number of checks should be zero):

![image](https://user-images.githubusercontent.com/28961086/49128677-4eb52f00-f281-11e8-96f5-5c89a24965fb.png)

**Comment by freefal** [comment]
Your write-up makes sense. Unfortunately, the current behavior of the app is consistent with the website and adding the expected behavior would involve saving additional client-side state, so I don't think this will change anytime soon.

**Comment by greg-finley-ck** [comment]
I noticed that this was fixed in web but still appears in the app.

**Comment by veloce** [comment]
Fixed now.
