### ISSUE TITLE
Tests are missing

### ISSUE THREAD

**Issue by sepiropht** [lichess-org/lichobile#920]
For the moment there is not so many tests in the mobile app. 
I found  [that](https://github.com/kentcdodds/dom-testing-library-with-anything/blob/master/mithril.test.js) and i will be very happy to contribute.
Can i try it ? If yes which part of the app should be test first ?

**Comment by freefal** [comment]
I'm not sure I follow. What would the purpose of the tests be?

**Comment by sepiropht** [comment]
It is always good to have some tests in your software, isn't it ?

**Comment by freefal** [comment]
Generally, yes. I'm just trying to understand what the proposed tests would
test.
