### ISSUE TITLE
[Bug] Back button terminates game immediatelly

### ISSUE THREAD

**Issue by MateMachine** [lichess-org/lichobile#985]
Lichess version: v6.1.3
Smartphone: Samsung Galaxy S8
Android version: 9
Rooted/CFW: No
-----------------------
Hello,

When I press the back button while I'm playing a match, the app gets terminated without any warning.
After I start the app again, I'm on the main menue.
The same happens when:
- I'm in the analysis board.
- I browse through settings
- play offline against the CPU

I'm sure in the previous version there was not such a problem.
Generally I was always able to go back to the previous matches or menues.

P.S. I'm not logged in - I use it only anonymously.

Can you check, please?

**Comment by freefal** [comment]
PR that I believe resolves this issue here: https://github.com/veloce/lichobile/pull/1022
